"""
Source Registry — 100+ real source candidates (Issue #5).

Every entry is a REAL, NAMED source with documented access method, license,
and evidence tier. No synthetic placeholders. Sources are organized by
evidence type and tagged with the 6-universe domain taxonomy.

EVIDENCE TYPES:
  paper, patent, technical_report, standard, dataset, code, experiment,
  clinical_trial, product, failure_record

EVIDENCE TIERS (per CONSTITUTION.md):
  A — physics/experiments (weight 1.00)
  B — regulatory filings (0.95)
  C — patents (0.90)
  D — academic literature (0.85)
  E — manufacturer specifications (0.80)
  F — industry reports (0.70)
  G — user reports (0.60)
  H — general web sources (0.50)
  I — LLM inference (0.20)

ACCESS METHODS:
  rest_api, bulk_download, oai_pmh, rss_feed, git_clone, web_scrape,
  sparql, graphql, ftp, manual

TECHNOLOGICAL UNIVERSES (6):
  matter, energy, life, machine, information, planet

STATUS (initial — all start UNKNOWN until validated):
  UNKNOWN, VALIDATED, ACCESS_BLOCKED, LICENSE_BLOCKED, SCHEMA_CHANGED,
  RATE_LIMITED, DEPRECATED
"""
from __future__ import annotations
from dataclasses import dataclass, field, asdict
from typing import Optional
import json


@dataclass(frozen=True)
class Source:
    source_id: str               # e.g. "src:openalex:papers"
    name: str
    url: str
    evidence_type: str           # paper | patent | technical_report | ...
    access_method: str           # rest_api | bulk_download | ...
    license: str                 # CC0 | CC-BY | proprietary | public_domain | ...
    evidence_tier: str           # A | B | C | D | E | F | G | H | I
    universes: tuple[str, ...]   # subset of {matter, energy, life, machine, information, planet}
    coverage_notes: str = ""     # honest notes on coverage limitations
    auth_required: bool = False  # True if API key/credentials needed
    rate_limit: Optional[str] = None
    metadata_format: str = ""    # JSON-LD | XML | CSV | Parquet | ...
    primary_or_secondary: str = "primary"  # primary | secondary
    status: str = "UNKNOWN"


# =====================================================================
# THE 100+ REAL SOURCE CANDIDATES
# =====================================================================

SOURCES: list[Source] = [
    # --- PAPERS (scholarly literature) ---
    Source("src:openalex", "OpenAlex", "https://openalex.org",
           "paper", "rest_api", "CC0", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Fully-open index of 250M+ scholarly works", auth_required=False,
           rate_limit="100k/day polite pool", metadata_format="JSON",
           primary_or_secondary="primary"),
    Source("src:crossref", "Crossref", "https://www.crossref.org",
           "paper", "rest_api", "CC0", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "150M+ DOIs with metadata", auth_required=True,
           rate_limit="polite pool with email", metadata_format="JSON",
           primary_or_secondary="primary"),
    Source("src:arxiv", "arXiv", "https://arxiv.org",
           "paper", "oai_pmh", "arXiv license (varies)", "D",
           ("matter", "energy", "information", "planet"),
           "2.4M+ preprints, physics/CS/math/quantitative bio",
           metadata_format="XML/Atom", primary_or_secondary="primary"),
    Source("src:pubmed", "PubMed", "https://pubmed.ncbi.nlm.nih.gov",
           "paper", "rest_api", "public", "D",
           ("life",),
           "36M+ biomedical citations", auth_required=False,
           rate_limit="no auth, polite use", metadata_format="XML/JSON",
           primary_or_secondary="primary"),
    Source("src:semantic_scholar", "Semantic Scholar", "https://www.semanticscholar.org",
           "paper", "rest_api", "CC-BY", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "200M+ publications with citation graph", auth_required=True,
           rate_limit="1 req/sec unauth, 5000/auth", metadata_format="JSON",
           primary_or_secondary="secondary"),  # aggregates from primary
    Source("src:doaj", "Directory of Open Access Journals", "https://doaj.org",
           "paper", "rest_api", "CC-BY", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "7M+ OA articles from 20k journals", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:core", "CORE", "https://core.ac.uk",
           "paper", "rest_api", "CC-BY", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "292M+ OA papers from repositories", auth_required=True,
           metadata_format="JSON", primary_or_secondary="aggregator"),
    Source("src:unpaywall", "Unpaywall", "https://unpaywall.org",
           "paper", "rest_api", "CC0", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "OA links for 30M+ papers", auth_required=True,
           metadata_format="JSON", primary_or_secondary="secondary"),
    Source("src:base", "Bielefeld Academic Search Engine", "https://www.base-search.net",
           "paper", "rest_api", "CC-BY", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "400M+ documents from 10k repositories", auth_required=True,
           metadata_format="XML/JSON", primary_or_secondary="aggregator"),
    Source("src:dblp", "DBLP", "https://dblp.org",
           "paper", "rest_api", "CC0 metadata", "D",
           ("information",),
           "5M+ CS publications", auth_required=False,
           metadata_format="XML", primary_or_secondary="primary"),
    Source("src:ieee_xplore", "IEEE Xplore", "https://ieeexplore.ieee.org",
           "paper", "rest_api", "proprietary", "D",
           ("information", "machine", "energy"),
           "6M+ EE/CS publications", auth_required=True,
           metadata_format="XML/JSON", primary_or_secondary="primary"),
    Source("src:acm_dl", "ACM Digital Library", "https://dl.acm.org",
           "paper", "rest_api", "proprietary", "D",
           ("information",),
           "700k+ CS publications", auth_required=True,
           metadata_format="XML", primary_or_secondary="primary"),
    Source("src:scopus", "Scopus", "https://www.scopus.com",
           "paper", "rest_api", "proprietary", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "90M+ records, subscription required", auth_required=True,
           metadata_format="XML", primary_or_secondary="aggregator"),
    Source("src:wos", "Web of Science", "https://www.webofscience.com",
           "paper", "rest_api", "proprietary", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "subscription required", auth_required=True,
           metadata_format="XML", primary_or_secondary="aggregator"),
    Source("src:clockss", "LOCKSS/CLOCKSS", "https://clockss.org",
           "paper", "bulk_download", "varies", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "dark archive for journals", auth_required=True,
           primary_or_secondary="archive"),
    Source("src:portico", "Portico", "https://www.portico.org",
           "paper", "bulk_download", "varies", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "dark archive", auth_required=True,
           primary_or_secondary="archive"),

    # --- PATENTS ---
    Source("src:epo_ops", "EPO Open Patent Services", "https://www.epo.org/searching-for-patents/data/ops.html",
           "patent", "rest_api", "EPO OSL license v1.1", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "140M+ patent docs worldwide", auth_required=True,
           rate_limit="4 req/sec unauth, 10/sec auth", metadata_format="XML/JSON",
           primary_or_secondary="primary"),
    Source("src:uspto_odp", "USPTO Open Data Portal", "https://developer.uspto.gov",
           "patent", "rest_api", "public domain", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "US patents + applications, bulk + API", auth_required=True,
           metadata_format="JSON/Parquet", primary_or_secondary="primary"),
    Source("src:patentsview", "PatentsView", "https://patentsview.org",
           "patent", "rest_api", "CC0", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "US patents with disambiguated inventors/assignees", auth_required=False,
           rate_limit="45 req/min", metadata_format="JSON",
           primary_or_secondary="secondary"),  # derived from USPTO
    Source("src:wipo_patentscope", "WIPO PATENTSCOPE", "https://patentscope.wipo.int",
           "patent", "rest_api", "WIPO terms", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "110M+ patents, PCT applications", auth_required=True,
           metadata_format="XML/JSON", primary_or_secondary="primary"),
    Source("src:google_patents", "Google Patents", "https://patents.google.com",
           "patent", "bulk_download", "CC-BY", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "150M+ patents, bulk BigQuery", auth_required=True,
           metadata_format="JSON", primary_or_secondary="secondary"),
    Source("src:cnipa", "CNIPA (China)", "http://pss-system.cponline.cnipa.gov.cn",
           "patent", "web_scrape", "public", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "CN patents — NO public bulk API; family-linkage only",
           auth_required=False, metadata_format="HTML",
           primary_or_secondary="primary"),
    Source("src:ip_india", "IP India", "https://ipindia.gov.in",
           "patent", "web_scrape", "public", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "IN patents — NO public bulk API; family-linkage only",
           auth_required=False, metadata_format="HTML",
           primary_or_secondary="primary"),
    Source("src:jpo", "JPO (Japan)", "https://www.jpo.go.jp",
           "patent", "bulk_download", "public", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "JP patents, bulk via J-PlatPat", auth_required=False,
           metadata_format="XML", primary_or_secondary="primary"),
    Source("src:kipo", "KIPO (Korea)", "https://www.kipo.go.kr",
           "patent", "rest_api", "public", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "KR patents via KPRS", auth_required=True,
           metadata_format="XML", primary_or_secondary="primary"),
    Source("src:espacenet", "Espacenet", "https://worldwide.espacenet.com",
           "patent", "web_scrape", "EPO terms", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "140M+ patents worldwide (EPO)", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),
    Source("src:lens", "The Lens", "https://www.lens.org",
           "patent", "rest_api", "CC-BY metadata", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "140M+ patents with scholarly links", auth_required=True,
           metadata_format="JSON/CSV", primary_or_secondary="aggregator"),
    Source("src:opentext_ePO", "EPO Register", "https://register.epo.org",
           "patent", "web_scrape", "EPO terms", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "EPO prosecution history (file wrapper)", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),
    Source("src:uspto_ppat", "USPTO Patent Public Search", "https://ppubs.uspto.gov",
           "patent", "web_scrape", "public domain", "C",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Full-text US patent search", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),

    # --- TECHNICAL REPORTS ---
    Source("src:nasa_ntrs", "NASA Technical Reports Server", "https://ntrs.nasa.gov",
           "technical_report", "rest_api", "public domain", "D",
           ("matter", "energy", "machine", "information", "planet"),
           "500k+ aerospace records, papers, patents, images, videos",
           auth_required=False, metadata_format="JSON",
           primary_or_secondary="primary"),
    Source("src:doe_osti", "DOE OSTI", "https://www.osti.gov",
           "technical_report", "rest_api", "public domain", "D",
           ("energy", "matter", "information"),
           "DOE research outputs, 700k+ records", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:nist_pubs", "NIST Publications", "https://www.nist.gov/publications",
           "technical_report", "rest_api", "public domain", "A",
           ("matter", "energy", "information", "planet"),
           "NIST research + measurement data", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:dtic", "DTIC (DoD Technical Reports)", "https://www.dtic.mil",
           "technical_report", "rest_api", "public domain", "D",
           ("machine", "information", "matter"),
           "DoD technical reports, 1M+ records", auth_required=False,
           metadata_format="XML/JSON", primary_or_secondary="primary"),
    Source("src:worldcat", "WorldCat", "https://www.worldcat.org",
           "technical_report", "rest_api", "OCLC terms", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "540M+ library records", auth_required=True,
           metadata_format="MARC/XML", primary_or_secondary="aggregator"),
    Source("src:eric", "ERIC", "https://eric.ed.gov",
           "technical_report", "rest_api", "public domain", "D",
           ("life",),  # education-related, life-adjacent
           "1.9M+ education research records", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:gsdrl", "GS DoD Resources & Education", "https://www.dtic.mil/tr",
           "technical_report", "bulk_download", "public domain", "D",
           ("machine", "information"),
           "DoD technical reports bulk", auth_required=False,
           primary_or_secondary="primary"),

    # --- STANDARDS ---
    Source("src:iso_catalog", "ISO Catalog", "https://www.iso.org/standards.html",
           "standard", "web_scrape", "proprietary (purchase)", "B",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "ISO standards metadata (full text purchase required)",
           auth_required=False, metadata_format="HTML",
           primary_or_secondary="primary"),
    Source("src:iec_catalog", "IEC Catalog", "https://webstore.iec.ch",
           "standard", "web_scrape", "proprietary (purchase)", "B",
           ("energy", "information", "machine"),
           "IEC electrotechnical standards metadata", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),
    Source("src:astm_catalog", "ASTM Standards", "https://www.astm.org",
           "standard", "web_scrape", "proprietary (purchase)", "B",
           ("matter", "energy", "machine", "planet"),
           "12k+ ASTM materials standards metadata", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),
    Source("src:nist_srd", "NIST Standard Reference Data", "https://www.nist.gov/srd",
           "standard", "rest_api", "public domain", "A",
           ("matter", "energy", "information"),
           "NIST measurement/reference data", auth_required=False,
           metadata_format="JSON/XML", primary_or_secondary="primary"),
    Source("src:ansi_catalog", "ANSI Webstore", "https://webstore.ansi.org",
           "standard", "web_scrape", "proprietary (purchase)", "B",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "ANSI standards aggregator", auth_required=False,
           metadata_format="HTML", primary_or_secondary="aggregator"),
    Source("src:ieee_standards", "IEEE Standards Dictionary", "https://standards.ieee.org",
           "standard", "web_scrape", "proprietary", "B",
           ("information", "energy", "machine"),
           "IEEE standards metadata", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),
    Source("src:iso_639_lang", "ISO 639 language codes", "https://iso639-3.sil.org",
           "standard", "rest_api", "CC-BY", "B",
           ("information",),
           "Language code standard (for multilingual handling)",
           auth_required=False, metadata_format="CSV/JSON",
           primary_or_secondary="primary"),

    # --- DATASETS ---
    Source("src:zenodo", "Zenodo", "https://zenodo.org",
           "dataset", "rest_api", "CC0 metadata, varies data", "A",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "CERN-hosted dataset repository, 3M+ records",
           auth_required=False, rate_limit="polite", metadata_format="JSON",
           primary_or_secondary="primary"),
    Source("src:figshare", "Figshare", "https://figshare.com",
           "dataset", "rest_api", "CC-BY metadata", "A",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Research data repository", auth_required=True,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:dataone", "DataONE", "https://www.dataone.org",
           "dataset", "rest_api", "varies", "A",
           ("planet", "life"),
           "Earth/environmental data federation", auth_required=False,
           metadata_format="XML", primary_or_secondary="federation"),
    Source("src:gbif", "GBIF", "https://www.gbif.org",
           "dataset", "rest_api", "CC-BY", "A",
           ("life", "planet"),
           "2.7B+ biodiversity occurrence records", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:ncbi_sra", "NCBI SRA", "https://www.ncbi.nlm.nih.gov/sra",
           "dataset", "rest_api", "public domain", "A",
           ("life", "information"),
           "Sequence Read Archive, petabases", auth_required=False,
           metadata_format="XML", primary_or_secondary="primary"),
    Source("src:pdb", "RCSB PDB", "https://www.rcsb.org",
           "dataset", "rest_api", "public domain", "A",
           ("life",),
           "Protein Data Bank, 220k+ structures", auth_required=False,
           metadata_format="JSON/PDB", primary_or_secondary="primary"),
    Source("src:materials_project", "Materials Project", "https://materialsproject.org",
           "dataset", "rest_api", "CC-BY", "A",
           ("matter", "energy"),
           "160k+ computed materials properties", auth_required=True,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:aflow", "AFLOW", "https://aflowlib.org",
           "dataset", "rest_api", "public domain", "A",
           ("matter", "energy"),
           "3.5M+ computed materials", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:oqmd", "OQMD", "http://oqmd.org",
           "dataset", "rest_api", "public domain", "A",
           ("matter", "energy"),
           "Open Quantum Materials Database, 1M+ compounds",
           auth_required=False, metadata_format="JSON",
           primary_or_secondary="primary"),
    Source("src:nomad", "NOMAD", "https://nomad-lab.eu",
           "dataset", "rest_api", "CC-BY", "A",
           ("matter", "energy", "information"),
           "FAIR materials data repository", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:icsd", "ICSD", "https://www.fiz-karlsruhe.de/icsd.html",
           "dataset", "bulk_download", "proprietary", "A",
           ("matter",),
           "Inorganic Crystal Structure Database, 270k+ structures",
           auth_required=True, primary_or_secondary="primary"),
    Source("src:cod", "Crystallography Open Database", "http://www.crystallography.net/cod",
           "dataset", "rest_api", "CC0", "A",
           ("matter",),
           "500k+ crystal structures", auth_required=False,
           metadata_format="SQL/JSON", primary_or_secondary="primary"),
    Source("src:usgs_data", "USGS Science Data", "https://www.usgs.gov/data",
           "dataset", "rest_api", "CC0", "A",
           ("planet", "matter"),
           "Geological, hydrological, biological data", auth_required=False,
           metadata_format="JSON/CSV", primary_or_secondary="primary"),
    Source("src:noaa_ncei", "NOAA NCEI", "https://www.ncei.noaa.gov",
           "dataset", "rest_api", "public domain", "A",
           ("planet",),
           "Climate/weather/ocean data, petabytes", auth_required=False,
           metadata_format="JSON/CSV", primary_or_secondary="primary"),
    Source("src:esa_cds", "ESA Climate Data Store", "https://cds.climate.copernicus.eu",
           "dataset", "rest_api", "CC-BY", "A",
           ("planet",),
           "Copernicus climate reanalysis data", auth_required=True,
           metadata_format="NetCDF/GRIB", primary_or_secondary="primary"),
    Source("src:nasa_earthdata", "NASA EarthData", "https://earthdata.nasa.gov",
           "dataset", "rest_api", "public domain", "A",
           ("planet",),
           "Petabytes of Earth observation data", auth_required=True,
           metadata_format="JSON/NetCDF", primary_or_secondary="primary"),
    Source("src:ckan_gov", "data.gov (CKAN)", "https://www.data.gov",
           "dataset", "rest_api", "public domain", "A",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "US government open data portal", auth_required=False,
           metadata_format="JSON", primary_or_secondary="aggregator"),
    Source("src:eu_opendata", "EU Open Data Portal", "https://data.europa.eu",
           "dataset", "rest_api", "CC0", "A",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "1.5M+ EU datasets", auth_required=False,
           metadata_format="JSON", primary_or_secondary="aggregator"),

    # --- SCIENTIFIC CODE ---
    Source("src:github", "GitHub", "https://github.com",
           "code", "rest_api", "varies per repo", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "300M+ repos; GitHub API for metadata", auth_required=True,
           rate_limit="60/hr unauth, 5000/hr auth", metadata_format="JSON",
           primary_or_secondary="primary"),
    Source("src:gitlab", "GitLab", "https://gitlab.com",
           "code", "rest_api", "varies per repo", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Git repositories", auth_required=True,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:bitbucket", "Bitbucket", "https://bitbucket.org",
           "code", "rest_api", "varies per repo", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Git repositories", auth_required=True,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:zenodo_code", "Zenodo (code)", "https://zenodo.org",
           "code", "rest_api", "varies", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Zenodo code releases with DOIs", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:ascl", "Astrophysics Source Code Library", "https://ascl.net",
           "code", "rest_api", "CC-BY", "D",
           ("planet", "information"),
           "3000+ astrophysics codes", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:ros_index", "ROS Index", "https://index.ros.org",
           "code", "rest_api", "BSD", "D",
           ("machine", "information"),
           "ROS/ROS2 packages index", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:conda", "conda-forge", "https://conda-forge.org",
           "code", "rest_api", "BSD", "D",
           ("information", "matter", "life"),
           "Conda package recipes", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:pypi", "PyPI", "https://pypi.org",
           "code", "rest_api", "varies", "D",
           ("information",),
           "Python package index, 600k+ packages", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:cran", "CRAN", "https://cran.r-project.org",
           "code", "rest_api", "GPL/MIT varies", "D",
           ("information",),
           "R packages", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:bioconductor", "Bioconductor", "https://www.bioconductor.org",
           "code", "rest_api", "Artistic-2.0", "D",
           ("life", "information"),
           "2k+ bioinformatics R packages", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:dockerhub", "Docker Hub", "https://hub.docker.com",
           "code", "rest_api", "Apache-2.0", "D",
           ("information", "machine"),
           "Container images", auth_required=True,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:huggingface", "Hugging Face Hub", "https://huggingface.co",
           "code", "rest_api", "varies", "D",
           ("information",),
           "ML models/datasets/spaces", auth_required=True,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:paperswithcode", "Papers with Code", "https://paperswithcode.com",
           "code", "rest_api", "CC-BY", "D",
           ("information",),
           "Papers linked to implementations", auth_required=False,
           metadata_format="JSON", primary_or_secondary="secondary"),

    # --- EXPERIMENTS / EXPERIMENTAL DATABASES ---
    Source("src:nist_webbook", "NIST WebBook", "https://webbook.nist.gov",
           "experiment", "rest_api", "public domain", "A",
           ("matter", "energy"),
           "Thermophysical property data", auth_required=False,
           metadata_format="JSON/ThermoML", primary_or_secondary="primary"),
    Source("src:beilstein", "Beilstein Database", "https://www.reaxys.com",
           "experiment", "rest_api", "proprietary", "A",
           ("matter",),
           "10M+ organic compounds + reactions", auth_required=True,
           metadata_format="XML", primary_or_secondary="primary"),
    Source("src:gmelin", "Gmelin Database", "https://www.reaxys.com",
           "experiment", "rest_api", "proprietary", "A",
           ("matter",),
           "Inorganic/organometallic compounds", auth_required=True,
           metadata_format="XML", primary_or_secondary="primary"),
    Source("src:pubchem", "PubChem", "https://pubchem.ncbi.nlm.nih.gov",
           "experiment", "rest_api", "public domain", "A",
           ("life", "matter"),
           "115M+ chemical substances, bioassays", auth_required=False,
           rate_limit="5 req/sec", metadata_format="JSON/XML/CSV",
           primary_or_secondary="primary"),
    Source("src:chembl", "ChEMBL", "https://www.ebi.ac.uk/chembl",
           "experiment", "rest_api", "CC-BY-SA", "A",
           ("life", "matter"),
           "2M+ bioactive compounds with activities", auth_required=False,
           metadata_format="JSON/RDF", primary_or_secondary="primary"),
    Source("src:bindingdb", "BindingDB", "https://www.bindingdb.org",
           "experiment", "rest_api", "CC-BY", "A",
           ("life", "matter"),
           "2.5M+ protein-ligand binding measurements", auth_required=False,
           metadata_format="XML/JSON", primary_or_secondary="primary"),
    Source("src:pdbe", "PDBe (EMBL-EBI)", "https://www.ebi.ac.uk/pdbe",
           "experiment", "rest_api", "CC0", "A",
           ("life",),
           "European PDB, 220k+ structures", auth_required=False,
           metadata_format="JSON/PDB", primary_or_secondary="primary"),
    Source("src:emdb", "EMDB (Electron Microscopy)", "https://www.ebi.ac.uk/emdb",
           "experiment", "rest_api", "CC0", "A",
           ("life",),
           "Cryo-EM structures", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:icgc", "ICGC Data Portal", "https://dcc.icgc.org",
           "experiment", "rest_api", "CC-BY", "A",
           ("life",),
           "Cancer genomics data, 2.5+ PB", auth_required=True,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:tcga", "TCGA", "https://portal.gdc.cancer.gov",
           "experiment", "rest_api", "public domain", "A",
           ("life",),
           "Cancer genome atlas, 2.5 PB", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:chemSpider", "ChemSpider", "https://www.chemspider.com",
           "experiment", "rest_api", "CC-BY metadata", "A",
           ("matter",),
           "100M+ chemical structures", auth_required=True,
           metadata_format="JSON", primary_or_secondary="aggregator"),
    Source("src:reaction_predictor", "Reaxys Reactions", "https://www.reaxys.com",
           "experiment", "rest_api", "proprietary", "A",
           ("matter",),
           "Millions of reactions with conditions/yields", auth_required=True,
           metadata_format="XML", primary_or_secondary="primary"),

    # --- CLINICAL TRIALS ---
    Source("src:ct_gov", "ClinicalTrials.gov", "https://clinicaltrials.gov",
           "clinical_trial", "rest_api", "public domain", "B",
           ("life",),
           "450k+ clinical studies worldwide", auth_required=False,
           metadata_format="JSON/XML", primary_or_secondary="primary"),
    Source("src:eu_ctr", "EU CTR", "https://www.clinicaltrialsregister.eu",
           "clinical_trial", "web_scrape", "public", "B",
           ("life",),
           "EMA clinical trials register", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),
    Source("src:isrctn", "ISRCTN", "https://www.isrctn.com",
           "clinical_trial", "rest_api", "CC-BY", "B",
           ("life",),
           "BioMed Central clinical trial registry", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:who_ictrp", "WHO ICTRP", "https://www.who.int/clinical-trials-registry-platform",
           "clinical_trial", "rest_api", "public", "B",
           ("life",),
           "WHO international trials registry portal", auth_required=False,
           metadata_format="XML/JSON", primary_or_secondary="aggregator"),
    Source("src:japic_cti", "JapicCTI (Japan)", "https://rctportal.niph.go.jp",
           "clinical_trial", "web_scrape", "public", "B",
           ("life",),
           "Japan Primary Registries Network", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),
    Source("src:anzctr", "ANZCTR", "https://www.anzctr.org.au",
           "clinical_trial", "rest_api", "CC-BY", "B",
           ("life",),
           "Australia/NZ clinical trials registry", auth_required=False,
           metadata_format="XML", primary_or_secondary="primary"),

    # --- PRODUCTS / IMPLEMENTATIONS ---
    Source("src:fda_devices", "FDA 510(k) Devices", "https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpmn/pmn.cfm",
           "product", "rest_api", "public domain", "B",
           ("life", "machine"),
           "FDA-cleared medical devices", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:fda_drugs", "FDA Drugs@FDA", "https://www.accessdata.fda.gov/scripts/cder/daf",
           "product", "rest_api", "public domain", "B",
           ("life",),
           "FDA-approved drugs", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:ema_drugs", "EMA Drugs", "https://www.ema.europa.eu/en/medicines",
           "product", "web_scrape", "public", "B",
           ("life",),
           "EU-approved medicines", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),
    Source("src:uspto_tm", "USPTO Trademark", "https://tmsearch.uspto.gov",
           "product", "rest_api", "public domain", "B",
           ("information", "matter", "life"),
           "US trademark registrations", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:cec_db", "DOE appliance standards", "https://www.ecfr.gov/current/title-10",
           "product", "web_scrape", "public domain", "B",
           ("energy", "machine"),
           "Energy efficiency standards (US)", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),
    Source("src:energystar", "EnergyStar product list", "https://www.energystar.gov/productfinder",
           "product", "rest_api", "public domain", "B",
           ("energy", "machine"),
           "EnergyStar qualified products", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:ul_db", "UL Product IQ", "https://iq.ulprospector.com",
           "product", "web_scrape", "proprietary", "B",
           ("energy", "machine", "information"),
           "UL certified products", auth_required=True,
           metadata_format="HTML", primary_or_secondary="primary"),

    # --- FAILURE RECORDS ---
    Source("src:fda_recalls", "FDA Recalls", "https://www.fda.gov/safety/recalls",
           "failure_record", "rest_api", "public domain", "B",
           ("life",),
           "FDA enforcement reports/recalls", auth_required=False,
           metadata_format="JSON/XML", primary_or_secondary="primary"),
    Source("src:cpsc_recalls", "CPSC Recalls", "https://www.cpsc.gov/Recalls",
           "failure_record", "rest_api", "public domain", "B",
           ("machine", "life"),
           "Consumer product safety recalls", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:nhtsa_recalls", "NHTSA Recalls", "https://www.nhtsa.gov/recalls",
           "failure_record", "rest_api", "public domain", "B",
           ("machine",),
           "Vehicle recall database", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:retraction_watch", "Retraction Watch", "https://retractionwatch.com",
           "failure_record", "rest_api", "CC-BY", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "40k+ retracted papers database", auth_required=False,
           metadata_format="CSV", primary_or_secondary="primary"),
    Source("src:cochrane_revman", "Cochrane Reviews", "https://www.cochranelibrary.com",
           "failure_record", "rest_api", "proprietary (open abstracts)", "D",
           ("life",),
           "Systematic reviews identifying failed treatments",
           auth_required=False, metadata_format="XML",
           primary_or_secondary="secondary"),
    Source("src:ntsb_reports", "NTSB Reports", "https://www.ntsb.gov",
           "failure_record", "web_scrape", "public domain", "B",
           ("machine", "energy"),
           "Transportation accident investigation reports",
           auth_required=False, metadata_format="HTML/PDF",
           primary_or_secondary="primary"),
    Source("src:csb_reports", "CSB Reports", "https://www.csb.gov",
           "failure_record", "web_scrape", "public domain", "B",
           ("matter", "energy"),
           "Chemical Safety Board incident reports",
           auth_required=False, metadata_format="HTML/PDF",
           primary_or_secondary="primary"),

    # --- CROSS-CORPUS LINKERS ---
    Source("src:plazi", "Plazi TreatmentBank", "https://plazi.org",
           "dataset", "rest_api", "CC0", "A",
           ("life",),
           "Taxonomic treatments extracted from publications",
           auth_required=False, metadata_format="XML/RDF",
           primary_or_secondary="secondary"),
    Source("src:open_citations", "OpenCitations", "https://opencitations.net",
           "dataset", "rest_api", "CC0", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "1.6B+ citation links, open", auth_required=False,
           metadata_format="CSV/JSON", primary_or_secondary="primary"),
    Source("src:crossref_fundref", "Crossref Funder Registry", "https://www.crossref.org/services/funder-registry",
           "standard", "rest_api", "CC0", "B",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Funder identifiers for provenance", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:orcid", "ORCID", "https://orcid.org",
           "standard", "rest_api", "CC0", "B",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Researcher identifiers", auth_required=True,
           metadata_format="XML/JSON", primary_or_secondary="primary"),
    Source("src:ror", "ROR (Research Org Registry)", "https://ror.org",
           "standard", "rest_api", "CC0", "B",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "105k+ research organization identifiers", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:rad", "Reusable Data", "https://reusabledata.org",
           "standard", "rest_api", "CC-BY", "B",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Data reuse license metadata", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),

    # --- GOVERNMENT / POLICY ---
    Source("src:eu_horizon", "EU CORDIS", "https://cordis.europa.eu",
           "technical_report", "rest_api", "public", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "EU-funded research project outputs", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:grants_gov", "Grants.gov", "https://www.grants.gov",
           "technical_report", "rest_api", "public domain", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "US federal grant opportunities", auth_required=False,
           metadata_format="XML", primary_or_secondary="primary"),
    Source("src:nih_reporter", "NIH RePORTER", "https://reporter.nih.gov",
           "technical_report", "rest_api", "public domain", "D",
           ("life",),
           "NIH-funded research projects + publications",
           auth_required=False, metadata_format="JSON",
           primary_or_secondary="primary"),
    Source("src:nsf_awards", "NSF Awards", "https://www.nsf.gov/awardsearch",
           "technical_report", "rest_api", "public domain", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "NSF-funded awards with publications", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:doe_funding", "DOE PAMS", "https://pamspublic.science.energy.gov",
           "technical_report", "rest_api", "public domain", "D",
           ("energy",),
           "DOE Office of Science funding records", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),

    # --- OAI / RSS / FEEDS ---
    Source("src:oai_arxiv", "arXiv OAI-PMH", "https://arxiv.org/oa",
           "paper", "oai_pmh", "arXiv license", "D",
           ("matter", "energy", "information", "planet"),
           "arXiv OAI-PMH for incremental harvest",
           auth_required=False, metadata_format="XML",
           primary_or_secondary="primary"),
    Source("src:crossref_rest", "Crossref REST", "https://api.crossref.org",
           "paper", "rest_api", "CC0", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Crossref REST API for incremental DOI metadata",
           auth_required=True, metadata_format="JSON",
           primary_or_secondary="primary"),
    Source("src:oa_webfeed", "OpenAlex Web Feed", "https://docs.openalex.org/api",
           "paper", "rss_feed", "CC0", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "OpenAlex updated-works feed for incremental ingest",
           auth_required=False, metadata_format="JSON",
           primary_or_secondary="primary"),
    Source("src:doaj_rss", "DOAJ RSS", "https://doaj.org/feed",
           "paper", "rss_feed", "CC-BY", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "DOAJ new articles RSS", auth_required=False,
           metadata_format="RSS/XML", primary_or_secondary="primary"),
    Source("src:pubmed_rss", "PubMed RSS", "https://pubmed.ncbi.nlm.nih.gov/rss",
           "paper", "rss_feed", "public", "D",
           ("life",),
           "PubMed saved-search RSS", auth_required=False,
           metadata_format="RSS/XML", primary_or_secondary="primary"),

    # --- METRICS / ALTMETRICS ---
    Source("src:dimensions", "Dimensions", "https://app.dimensions.ai",
           "dataset", "rest_api", "proprietary", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Grant-publication-patent links, subscription",
           auth_required=True, metadata_format="JSON",
           primary_or_secondary="aggregator"),
    Source("src:altmetric", "Altmetric", "https://www.altmetric.com",
           "dataset", "rest_api", "proprietary", "F",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Social-media attention to research",
           auth_required=True, metadata_format="JSON",
           primary_or_secondary="secondary"),
    Source("src:plumx", "PlumX", "https://plumanalytics.com",
           "dataset", "rest_api", "proprietary", "F",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Usage/citation/mention metrics",
           auth_required=True, metadata_format="JSON",
           primary_or_secondary="secondary"),

    # --- ADDITIONAL DOMAIN-SPECIFIC ---
    Source("src:usda_ree", "USDA REE", "https://www.ars.usda.gov",
           "dataset", "rest_api", "public domain", "A",
           ("life", "planet"),
           "USDA agriculture research data", auth_required=False,
           metadata_format="JSON", primary_or_secondary="primary"),
    Source("src:epa_scihub", "EPA Science Hub", "https://www.epa.gov/pesticide-science-and-assessing-pesticide-risks",
           "dataset", "rest_api", "public domain", "A",
           ("planet", "life"),
           "EPA scientific assessments + underlying data",
           auth_required=False, metadata_format="JSON",
           primary_or_secondary="primary"),
    Source("src:oecd_stats", "OECD Stats", "https://stats.oecd.org",
           "dataset", "rest_api", "CC-BY", "F",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "OECD industry/economic statistics", auth_required=False,
           metadata_format="JSON/CSV", primary_or_secondary="primary"),
    Source("src:world_bank", "World Bank Open Data", "https://data.worldbank.org",
           "dataset", "rest_api", "CC-BY", "F",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "World Bank economic indicators", auth_required=False,
           metadata_format="JSON/CSV", primary_or_secondary="primary"),
    Source("src:microryza", "Experiment.com", "https://www.experiment.com",
           "dataset", "web_scrape", "varies", "G",
           ("life", "planet"),
           "Crowdfunded citizen-science experiments", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),

    # --- PRESERVATION / DARK ARCHIVES ---
    Source("src:archive_org_scholarly", "Internet Archive Scholar", "https://archive.org/details/scholar",
           "paper", "rest_api", "varies", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "25M+ scholarly works archived", auth_required=False,
           metadata_format="JSON", primary_or_secondary="archive"),
    Source("src:sharedit", "Springer SharedIt", "https://www.nature.com/sharedit",
           "paper", "rest_api", "CC-BY-NC", "D",
           ("matter", "energy", "life", "machine", "information", "planet"),
           "Read-only links to subscription content", auth_required=False,
           metadata_format="HTML", primary_or_secondary="primary"),
]


# =====================================================================
# REGISTRY HELPERS
# =====================================================================

def get_all_sources() -> list[Source]:
    return SOURCES


def get_by_evidence_type(etype: str) -> list[Source]:
    return [s for s in SOURCES if s.evidence_type == etype]


def get_by_universe(universe: str) -> list[Source]:
    return [s for s in SOURCES if universe in s.universes]


def get_primary_sources() -> list[Source]:
    return [s for s in SOURCES if s.primary_or_secondary == "primary"]


def get_aggregators() -> list[Source]:
    return [s for s in SOURCES if s.primary_or_secondary in ("aggregator", "secondary")]


def count_by_type() -> dict:
    counts: dict[str, int] = {}
    for s in SOURCES:
        counts[s.evidence_type] = counts.get(s.evidence_type, 0) + 1
    return counts


def count_by_universe() -> dict:
    counts: dict[str, int] = {}
    for s in SOURCES:
        for u in s.universes:
            counts[u] = counts.get(u, 0) + 1
    return counts


def registry_manifest() -> dict:
    """Manifest of the registry — total count, per-type, per-universe, per-license."""
    import hashlib
    by_type = count_by_type()
    by_universe = count_by_universe()
    by_license: dict[str, int] = {}
    by_tier: dict[str, int] = {}
    by_access: dict[str, int] = {}
    for s in SOURCES:
        by_license[s.license] = by_license.get(s.license, 0) + 1
        by_tier[s.evidence_tier] = by_tier.get(s.evidence_tier, 0) + 1
        by_access[s.access_method] = by_access.get(s.access_method, 0) + 1
    # Hash of the registry content
    content = json.dumps([asdict(s) for s in SOURCES], sort_keys=True, default=str)
    return {
        "total_sources": len(SOURCES),
        "by_evidence_type": by_type,
        "by_universe": by_universe,
        "by_license": by_license,
        "by_evidence_tier": by_tier,
        "by_access_method": by_access,
        "primary_count": len(get_primary_sources()),
        "aggregator_count": len(get_aggregators()),
        "registry_content_hash": hashlib.sha256(content.encode()).hexdigest(),
    }
