"""
Test the BACON law derivation engine (cycle 50).

Per CONSTITUTION.md Law 8 (Verification Standard): no "verified" label
without a successful prediction, a failed prediction, and replayable
evidence. This test file is the replayable evidence for BACON.

Per ANTI_ENTROPY.md "Use the word 'engine' honestly": the three
conditions for calling a module an "engine" are:
  1. Explicit model.  ✓ candidate law forms (linear, power, etc.)
  2. Empirical validation.  ✓ this test file, against real formula data
  3. Reproducible results.  ✓ pure functions, deterministic, no RNG

Per the falsifiability criterion in BACON: a law with R² < 0.5 is
rejected. This test verifies that:
  - Real data: a law is discovered (R² ≥ 0.5)
  - Random data: NO law is discovered (R² < 0.5 for every candidate)
"""
import math
import sys
import pathlib

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from invention_compiler.bacon_engine import (
    discover_law, discover_laws_from_dataset, DiscoveredLaw,
    stull_wet_bulb_dataset, stefan_boltzmann_dataset, pcm_latent_heat_dataset,
    R2_FALSIFIABILITY_THRESHOLD, CANDIDATE_LAWS,
)


class TestBaconEngineArchitecture:
    """Verify the engine's structure and the three 'engine honestly' conditions."""

    def test_bacon_engine_has_explicit_candidate_law_forms(self):
        """Condition 1: Explicit model. BACON must have explicit law forms."""
        assert len(CANDIDATE_LAWS) >= 5, "expected at least 5 candidate law forms"
        names = [c.name for c in CANDIDATE_LAWS]
        # Must include the canonical simple forms
        assert "linear" in names
        assert "power" in names
        assert "exponential" in names
        # Each candidate must have name, form, fit_func, param_names
        for c in CANDIDATE_LAWS:
            assert c.name
            assert c.form
            assert callable(c.fit_func)
            assert isinstance(c.param_names, list)
            assert len(c.param_names) >= 1

    def test_bacon_engine_is_reproducible(self):
        """Condition 3: Reproducible. Same inputs → same outputs (byte-exact)."""
        xs = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]
        ys = [2.0 * x + 1.0 for x in xs]  # exactly linear
        law1 = discover_law(xs, ys, x_label="x", y_label="y")
        law2 = discover_law(xs, ys, x_label="x", y_label="y")
        assert law1 is not None
        assert law2 is not None
        # Byte-exact same result
        assert law1.name == law2.name
        assert law1.params == law2.params
        assert law1.r2 == law2.r2

    def test_bacon_engine_has_falsifiability_threshold(self):
        """Per 'no data, say no data': a weak fit must be rejected."""
        assert R2_FALSIFIABILITY_THRESHOLD >= 0.5, (
            "falsifiability threshold must be at least 0.5 — a law with R²<0.5 "
            "is no better than chance and must not be reported"
        )


class TestBaconOnRealStefanBoltzmannData:
    """BACON vs Stefan-Boltzmann radiative cooling — the Kepler test.

    The Stefan-Boltzmann law is Q = εσA(T_s⁴ - T_sky⁴). With T_sky held
    constant, Q is approximately a power law in T_s with exponent 4 (and
    a constant offset from T_sky⁴). Over a narrow range, a quadratic
    approximation also fits very well — BACON should discover SOMETHING
    with high R². The exact form it picks is less important than that
    it picks a law with R² ≥ 0.95.
    """

    def test_stefan_boltzmann_dataset_is_real(self):
        """Verify the dataset is generated by the real formula, not synthetic."""
        data = stefan_boltzmann_dataset(n_points=5)
        assert "T_surface_K" in data
        assert "Q_W" in data
        assert len(data["T_surface_K"]) == 5
        assert len(data["Q_W"]) == 5
        # Sanity check: at T_surface = 280 K, Q should be small (negative = net cooling)
        # because T_surface < T_sky + small offset → Q is cooling-dominated
        # at T_surface = 380 K, Q should be large positive (heating-dominated)
        assert data["Q_W"][0] < data["Q_W"][-1], (
            "Q should increase with T_surface (Stefan-Boltzmann is monotonic in T⁴)"
        )

    def test_bacon_discovers_law_for_stefan_boltzmann(self):
        """BACON must discover a law with R² ≥ 0.95 on Stefan-Boltzmann data."""
        data = stefan_boltzmann_dataset(n_points=15)
        law = discover_law(data["T_surface_K"], data["Q_W"],
                           x_label="T_surface_K", y_label="Q_W")
        assert law is not None, (
            "BACON should have discovered a law for Stefan-Boltzmann data — "
            "the data is genuinely a smooth function of T, so R² should exceed 0.5"
        )
        assert law.r2 >= 0.95, (
            f"discovered law R²={law.r2:.4f} < 0.95 — Stefan-Boltzmann data is "
            f"a clean physical law; BACON should fit it well"
        )
        assert law.n_points == 15
        assert len(law.residuals) == 15
        assert law.falsifiable_by  # must have a falsifier

    def test_bacon_picks_simplest_high_r2_law(self):
        """Per Occam's razor: BACON picks the simplest form (linear before quadratic).

        When two laws both achieve R² ≥ 0.99, BACON should prefer the simpler
        one. The candidate order has 'linear' first, then 'inverse',
        'logarithmic', 'power', 'exponential', 'quadratic'.
        """
        # Construct data that fits both linear and quadratic perfectly
        # (because the true form is linear, the quadratic fit will have a≈0)
        xs = [1.0, 2.0, 3.0, 4.0, 5.0]
        ys = [2.0 * x + 1.0 for x in xs]
        law = discover_law(xs, ys, x_label="x", y_label="y")
        assert law is not None
        assert law.name == "linear", (
            f"BACON should pick 'linear' for exactly-linear data, "
            f"got '{law.name}' (R²={law.r2:.4f})"
        )


class TestBaconOnRealPCMData:
    """BACON vs PCM latent heat sizing — the linear test.

    pcm_latent_heat_sizing: m = (Q * t * 3600) / L
    Holding t and L constant, m is EXACTLY linear in Q. BACON should
    discover the linear law with R² = 1.0000 (no residual).
    """

    def test_pcm_dataset_is_real(self):
        """Verify the dataset comes from the real PCM formula."""
        data = pcm_latent_heat_dataset(n_points=5)
        assert "Q_daily_W" in data
        assert "m_pcm_kg" in data
        # Verify one point by hand
        # m = (Q * t * 3600) / L = (50 * 8 * 3600) / 200000 = 7.2 kg
        expected_first = 50 * 8 * 3600 / 200_000
        assert abs(data["m_pcm_kg"][0] - expected_first) < 1e-9, (
            f"PCM data point 0: expected {expected_first}, got {data['m_pcm_kg'][0]}"
        )

    def test_bacon_discovers_exact_linear_law_for_pcm(self):
        """BACON must discover linear law with R² ≈ 1.0 for PCM data."""
        data = pcm_latent_heat_dataset(n_points=10)
        law = discover_law(data["Q_daily_W"], data["m_pcm_kg"],
                           x_label="Q_daily_W", y_label="m_pcm_kg")
        assert law is not None
        assert law.name == "linear", (
            f"expected 'linear', got '{law.name}'"
        )
        assert law.r2 >= 0.9999, (
            f"PCM formula is exactly linear; R² should be 1.0, got {law.r2:.6f}"
        )
        # Verify the slope matches: m = (t * 3600 / L) * Q
        # t=8 hours, L=200000 J/kg → slope = 8 * 3600 / 200000 = 0.144
        assert abs(law.params[0] - 0.144) < 1e-6, (
            f"slope should be 0.144 (8*3600/200000), got {law.params[0]}"
        )
        # Intercept should be ~0
        assert abs(law.params[1]) < 1e-9, (
            f"intercept should be 0 (formula has no offset), got {law.params[1]}"
        )


class TestBaconOnStullWetBulbData:
    """BACON vs Stull wet-bulb — the multi-variate test.

    Stull's formula: T_wb = f(T, RH) — depends on BOTH variables.
    Single-variable BACON cannot capture the full law, but should
    discover a partial law (T_wb is roughly linear in T with R² ≈ 0.95
    when RH is held constant, or with multi-variate noise when RH varies).
    """

    def test_stull_dataset_is_real(self):
        """Verify the dataset comes from the Stull formula."""
        data = stull_wet_bulb_dataset(n_points=4)
        assert "T_dry_C" in data
        assert "RH_pct" in data
        assert "T_wet_C" in data
        assert len(data["T_dry_C"]) >= 4

    def test_bacon_discovers_partial_law_for_stull(self):
        """BACON should discover a partial law (R² ≥ 0.7) even with RH variation.

        T_wb is roughly linear in T (with weak RH dependence). Single-variable
        BACON will not achieve R²=1.0 because RH is also varying in the dataset.
        """
        data = stull_wet_bulb_dataset(n_points=25)
        # Varying both T and RH
        law = discover_law(data["T_dry_C"], data["T_wet_C"],
                           x_label="T_dry_C", y_label="T_wet_C")
        # Should still find a partial law with R² >= 0.7
        # (because T is the dominant variable)
        assert law is not None, (
            "BACON should find SOME law even with multi-variate noise"
        )
        assert law.r2 >= 0.7, (
            f"expected R² ≥ 0.7 for Stull T-only fit, got {law.r2:.4f}"
        )


class TestBaconHonestyOnRandomData:
    """Per 'no data, say no data': random data must produce NO law.

    This is the falsifiability test. If BACON 'discovers' a law for random
    noise, the engine is broken — it would be a hallucination, not
    induction.
    """

    def test_bacon_rejects_random_data(self):
        """Random noise must produce NO discovered law (R² < threshold for all)."""
        # Deterministic "random-ish" sequence (no RNG per the "use the word
        # 'engine' honestly" reproducibility rule) using a simple hash.
        xs = [float(i) for i in range(1, 21)]
        # y values that are NOT a function of x (deterministic noise)
        ys = [3.14 * (i * 7919 % 100) / 100.0 for i in range(1, 21)]
        law = discover_law(xs, ys, x_label="x", y_label="y_noise")
        # Either no law is returned (preferred) or it has R² < 0.5
        if law is not None:
            assert law.r2 < R2_FALSIFIABILITY_THRESHOLD, (
                f"BACON should not discover a law for noise; got {law.name} "
                f"with R²={law.r2:.4f} which exceeds the threshold "
                f"{R2_FALSIFIABILITY_THRESHOLD}. The engine is overfitting."
            )
        # If law is None, that's the PASS outcome.

    def test_bacon_rejects_short_data(self):
        """BACON must refuse to discover a law from < 3 data points."""
        xs = [1.0, 2.0]
        ys = [3.0, 5.0]
        law = discover_law(xs, ys, x_label="x", y_label="y")
        assert law is None, (
            "BACON must not fit a 2-parameter law to < 3 points — "
            "it's mathematically underdetermined"
        )


class TestBaconMultivariateDiscovery:
    """discover_laws_from_dataset: try multiple independent variables."""

    def test_discover_laws_from_dataset_finds_best_predictor(self):
        """When given a multi-variate dataset, find the best single predictor."""
        # Construct data where y is linearly dependent on x1 but not x2
        xs1 = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]
        xs2 = [3.14, 1.59, 2.65, 3.58, 9.79, 3.23, 8.46, 2.64]
        ys = [2.0 * x + 1.0 for x in xs1]
        dataset = {"x1": xs1, "x2": xs2, "y": ys}
        results = discover_laws_from_dataset(dataset, target_var="y")
        assert "x1" in results
        assert "x2" in results
        assert results["x1"] is not None
        assert results["x1"].r2 >= 0.999, (
            f"x1 should fit perfectly (R²=1.0), got {results['x1'].r2:.4f}"
        )
        # x2 should not fit as well (random data)
        if results["x2"] is not None:
            assert results["x2"].r2 < results["x1"].r2, (
                "x1 (the true predictor) should fit better than x2 (noise)"
            )


class TestBaconLawDataclass:
    """Verify the DiscoveredLaw dataclass can be serialized for ledger recording."""

    def test_discovered_law_to_dict_round_trip(self):
        """to_dict must produce a JSON-serializable dict."""
        data = pcm_latent_heat_dataset(n_points=10)
        law = discover_law(data["Q_daily_W"], data["m_pcm_kg"],
                           x_label="Q", y_label="m")
        assert law is not None
        d = law.to_dict()
        assert "name" in d
        assert "form" in d
        assert "params" in d
        assert "r2" in d
        assert "n_points" in d
        assert "falsifiable_by" in d
        assert "max_residual" in d
        # Must be JSON-serializable
        import json
        json.dumps(d)  # raises if not serializable

    def test_discovered_law_str_is_human_readable(self):
        """__str__ must produce a readable summary."""
        data = pcm_latent_heat_dataset(n_points=5)
        law = discover_law(data["Q_daily_W"], data["m_pcm_kg"])
        assert law is not None
        s = str(law)
        assert "DiscoveredLaw" in s
        assert "linear" in s
        assert "R²=" in s
