"""Tests: R4.1A Power Analysis — certified finite-sample joint-distribution
power enumerator with polynomial root-finding.

Per audit round 35 (R4.1 freeze-block audit):

    "Minimizing discordant-pair count does not necessarily minimize
     power for a composite decision rule. Power must be evaluated over
     the complete joint outcome distribution and the complete
     preregistered decision function."

Per audit round 36 (R4.1A certification audit):

    "A 1001-point p11 grid is not an exact enumeration of the joint
     model. For fixed (pe, pr), Power(p11) is a polynomial in p11 of
     degree <= N. Construct the polynomial, differentiate it, find all
     stationary points, evaluate at endpoints + stationary points.
     That gives a CERTIFIED global extremum."

    "The Type-I claim 'global max = 0.0059' is over tested nulls, not
     the continuous null space. Distinguish 'max among evaluated null
     scenarios' from 'global upper bound'."

Test categories:
    1. Probability mass conservation — sum over all (b, c) = 1.0
    2. Joint distribution constraints — p10 + p11 = pe, p01 + p11 = pr
    3. Power range — power in [0, 1] for every scenario
    4. Reference vector cross-check — script uses the SAME estimator
       as r4_reference_vectors.py (no drift)
    5. Extrema are actual min/max — search the interior, not just
       endpoints (the central statistical correction)
    6. p11 feasible interval — bounds are correct
    7. Combined rule matches protocol — passes == (p<0.05 AND CI>0.20)
    8. No handwritten power table — JSON is generated by the script
    9. Audit-number reproduction — match the values the external
       auditor independently calculated
   10. Statistical lesson recorded
   11. Polynomial construction correctness — polynomial(pe,pr)(p11)
       matches direct computation for all tested (pe, pr, p11)
   12. Certified extrema — certified method agrees with grid search,
       polynomial degree <= N, stationary points in feasible interval
   13. Type-I reporting distinction — artifact distinguishes
       tested-scenario max from global upper bound
"""
import json
import importlib.util
import math
import sys
from pathlib import Path

import pytest
from scipy.stats import binom

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))

# Import the power analysis module.
spec = importlib.util.spec_from_file_location(
    "r4_1_power_analysis",
    REPO / "scripts" / "r4_1_power_analysis.py",
)
r4_1 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(r4_1)

OUTPUT = (
    REPO / "experiments" / "measurement_discrimination"
    / "r4_1_power_analysis.json"
)
REFERENCE_VECTORS = (
    REPO / "experiments" / "measurement_discrimination"
    / "r4_reference_vectors.json"
)


# =====================================================================
# CATEGORY 1: PROBABILITY MASS CONSERVATION
# =====================================================================

class TestProbabilityMassConservation:
    """The multinomial marginal over (b, c) must sum to 1.0 for every
    admissible (p10, p01) pair. If it does not, the enumerator is
    missing outcomes and every power calculation is wrong."""

    @pytest.mark.parametrize("p10,p01", [
        (0.5, 0.1),    # R4.1 row 1 at p11=0
        (0.4, 0.0),    # R4.1 row 1 at p11=0.1
        (0.6, 0.05),
        (0.3, 0.0),
        (0.1, 0.1),    # symmetric
        (0.0, 0.0),    # degenerate: all concordant
        (0.5, 0.5),    # degenerate: no concordant
    ])
    def test_probability_mass_equals_one(self, p10, p01):
        """sum_{b, c : b+c <= N} P(b, c) must equal 1.0."""
        if p10 + p01 > 1.0 + 1e-12:
            pytest.skip("infeasible probability combination")
        total = sum(
            r4_1.multinomial_pmf_b_c(b, c, p10, p01, r4_1.N)
            for b in range(r4_1.N + 1)
            for c in range(r4_1.N + 1 - b)
        )
        assert abs(total - 1.0) < 1e-9, (
            f"Probability mass does not sum to 1.0 for "
            f"(p10={p10}, p01={p01}): got {total}"
        )

    def test_probability_mass_one_at_degenerate_p11(self):
        """When p11 = min(pe, pr) = pr (so p01 = 0), all discordant
        mass is on (b, 0). The sum over (b, 0) must equal
        sum_{b=0}^{N} Binom(N, p10) = 1.0."""
        pe, pr = 0.5, 0.1
        p11 = min(pe, pr)  # = 0.1
        p10 = pe - p11     # = 0.4
        p01 = pr - p11     # = 0.0
        total = sum(
            r4_1.multinomial_pmf_b_c(b, 0, p10, p01, r4_1.N)
            for b in range(r4_1.N + 1)
        )
        assert abs(total - 1.0) < 1e-9


# =====================================================================
# CATEGORY 2: JOINT DISTRIBUTION CONSTRAINTS
# =====================================================================

class TestJointDistributionConstraints:
    """The marginal-probability constraints p10 + p11 = pe and
    p01 + p11 = pr must hold for every admissible p11."""

    @pytest.mark.parametrize("pe,pr", [
        (0.5, 0.1), (0.6, 0.05), (0.7, 0.1), (0.3, 0.05),
    ])
    def test_marginal_constraints_hold(self, pe, pr):
        lo, hi = r4_1.feasible_p11_interval(pe, pr)
        # Sample several p11 values in the interior.
        for i in range(11):
            p11 = lo + (hi - lo) * i / 10
            p00, p01, p10, p11_actual = r4_1.joint_from_p11(pe, pr, p11)
            assert abs((p10 + p11_actual) - pe) < 1e-9, (
                f"p10 + p11 != pe: {p10} + {p11_actual} != {pe}"
            )
            assert abs((p01 + p11_actual) - pr) < 1e-9, (
                f"p01 + p11 != pr: {p01} + {p11_actual} != {pr}"
            )
            assert abs((p00 + p01 + p10 + p11_actual) - 1.0) < 1e-9, (
                f"Probabilities do not sum to 1: "
                f"{p00} + {p01} + {p10} + {p11_actual} = "
                f"{p00 + p01 + p10 + p11_actual}"
            )
            assert p00 >= -1e-12, f"p00 < 0: {p00}"
            assert p01 >= -1e-12, f"p01 < 0: {p01}"
            assert p10 >= -1e-12, f"p10 < 0: {p10}"
            assert p11_actual >= -1e-12, f"p11 < 0: {p11_actual}"


# =====================================================================
# CATEGORY 3: POWER RANGE
# =====================================================================

class TestPowerRange:
    """Power is a probability and must lie in [0, 1]."""

    @pytest.mark.parametrize("pe,pr", r4_1.POWER_SCENARIOS + r4_1.TYPE_I_SCENARIOS)
    def test_power_between_zero_and_one(self, pe, pr):
        row = r4_1.search_power_extrema(pe, pr)
        assert 0.0 <= row["power_min"] <= 1.0, (
            f"power_min out of [0,1]: {row['power_min']}"
        )
        assert 0.0 <= row["power_max"] <= 1.0, (
            f"power_max out of [0,1]: {row['power_max']}"
        )
        assert row["power_min"] <= row["power_max"] + 1e-9, (
            f"power_min > power_max: {row['power_min']} > {row['power_max']}"
        )

    def test_power_at_null_is_zero_when_peq_zero(self):
        """If pe = pr = 0, every outcome is (b=0, c=0, n_d=0).
        passes(0, 0) = (1.0 < 0.05) AND (CI_lower > 0.20) = False.
        Power = 0."""
        row = r4_1.search_power_extrema(0.0, 0.0)
        assert row["power_min"] == 0.0
        assert row["power_max"] == 0.0


# =====================================================================
# CATEGORY 4: REFERENCE VECTOR CROSS-CHECK
# =====================================================================

class TestReferenceVectorsMatch:
    """The power script must use the SAME estimator as
    r4_reference_vectors.py. Drift between the two would silently
    invalidate every power number."""

    def test_estimator_imported_not_reimplemented(self):
        """mcnemar_analysis must be sourced from
        r4_reference_vectors.py, not re-implemented in the power
        script. We verify by checking that the function source code
        is identical in both modules — a stronger guarantee than
        object identity, which fails because importlib creates fresh
        module objects on each load."""
        import inspect
        spec_rv = importlib.util.spec_from_file_location(
            "r4_reference_vectors",
            REPO / "scripts" / "r4_reference_vectors.py",
        )
        rv = importlib.util.module_from_spec(spec_rv)
        spec_rv.loader.exec_module(rv)
        src_in_power = inspect.getsource(r4_1.mcnemar_analysis)
        src_in_reference = inspect.getsource(rv.mcnemar_analysis)
        assert src_in_power == src_in_reference, (
            "mcnemar_analysis source code differs between "
            "r4_1_power_analysis.py and r4_reference_vectors.py. "
            "The power script must use the SAME estimator — single "
            "source of truth."
        )
        # Additionally, verify the power script does NOT define its
        # own mcnemar_analysis (it should only import it).
        power_src = (REPO / "scripts" / "r4_1_power_analysis.py").read_text()
        # The script should not contain a 'def mcnemar_analysis' line.
        assert "def mcnemar_analysis" not in power_src, (
            "r4_1_power_analysis.py contains 'def mcnemar_analysis' — "
            "the estimator must be IMPORTED, not re-defined."
        )

    @pytest.mark.parametrize("b,c", [(9, 1), (12, 1), (8, 2), (14, 0)])
    def test_individual_vectors_match_committed(self, b, c):
        """Each frozen vector must match the committed JSON exactly."""
        committed = json.loads(REFERENCE_VECTORS.read_text())
        committed_vec = next(
            v for v in committed["vectors"] if v["b"] == b and v["c"] == c
        )
        actual = r4_1.mcnemar_analysis(b, c, r4_1.N)
        for key in ("b", "c", "N", "n_d", "theta_hat",
                    "p_one_sided", "ci_lower", "ci_upper", "passes"):
            assert actual[key] == committed_vec[key], (
                f"Mismatch on (b={b}, c={c}) key '{key}': "
                f"script={actual[key]!r}, committed={committed_vec[key]!r}"
            )

    def test_cross_check_function_runs_clean(self):
        """The cross-check function in the script must pass without
        raising. This is the function the main script calls before
        generating the JSON."""
        assert r4_1.cross_check_reference_vectors() is True


# =====================================================================
# CATEGORY 5: EXTREMA ARE ACTUAL MIN/MAX
# =====================================================================

class TestExtremaAreActualMinMax:
    """The central statistical correction: extrema are NOT assumed to
    occur at endpoints. The script must search the interior.

    This is the test that catches the R4.1 defect: R4.1 assumed
    p11 = min(pe, pr) gives the worst case and p11 = 0 gives the best
    case. That assumption is invalid for the combined decision rule.
    """

    def test_search_uses_dense_grid(self):
        """The script must evaluate power at > 2 points (not just
        endpoints). A grid of P11_GRID_SIZE = 1001 is used."""
        assert r4_1.P11_GRID_SIZE > 100, (
            "Grid must be dense (>100 points), not just endpoints."
        )

    def test_pe040_pr010_max_is_at_interior(self):
        """For pe=0.40, pr=0.10, theta=0.30, the power maximum is at
        an INTERIOR point of the feasible p11 interval, not at an
        endpoint. This is direct mechanical proof that endpoint-only
        reasoning is invalid.

        Reproduction: at the time of writing, the argmax p11 ≈ 0.0474,
        which is in the interior of [0, 0.1]."""
        row = r4_1.search_power_extrema(0.40, 0.10)
        assert row["p11_lo"] < row["p11_at_max"] < row["p11_hi"], (
            f"For pe=0.40, pr=0.10, the power MAXIMUM must be at an "
            f"interior point. Got p11_at_max={row['p11_at_max']} "
            f"in [{row['p11_lo']}, {row['p11_hi']}]."
        )

    def test_pe050_pr010_min_is_at_p11_zero_not_at_min(self):
        """For pe=0.50, pr=0.10, theta=0.40 (the FIRST row of R4.1's
        table), R4.1 claimed the worst case is at p11 = min(pe, pr) = 0.1.

        Mechanically, the worst case is at p11 = 0, NOT at p11 = 0.1.
        This is the row that 'is enough to kill the freeze' per the
        external audit."""
        row = r4_1.search_power_extrema(0.50, 0.10)
        assert row["p11_at_min"] == 0.0, (
            f"For pe=0.50, pr=0.10, the power MINIMUM is at p11=0 "
            f"(not at p11=min(pe,pr)=0.1 as R4.1 claimed). "
            f"Got p11_at_min={row['p11_at_min']}."
        )
        assert row["p11_at_max"] == 0.1, (
            f"For pe=0.50, pr=0.10, the power MAXIMUM is at p11=0.1 "
            f"(which R4.1 thought was the WORST case). "
            f"Got p11_at_max={row['p11_at_max']}."
        )

    def test_extrema_are_global_not_local(self):
        """For each scenario, verify that no point on the grid gives
        power below power_min or above power_max. This catches
        off-by-one errors in the argmin/argmax search."""
        for pe, pr in r4_1.POWER_SCENARIOS:
            row = r4_1.search_power_extrema(pe, pr)
            lo, hi = r4_1.feasible_p11_interval(pe, pr)
            # Re-evaluate at 50 random-ish points across the interval.
            for i in range(50):
                p11 = lo + (hi - lo) * i / 49
                p = r4_1.power_at_p11(pe, pr, p11)
                assert p >= row["power_min"] - 1e-9, (
                    f"Found power {p} below reported power_min "
                    f"{row['power_min']} at p11={p11} for "
                    f"pe={pe}, pr={pr}"
                )
                assert p <= row["power_max"] + 1e-9, (
                    f"Found power {p} above reported power_max "
                    f"{row['power_max']} at p11={p11} for "
                    f"pe={pe}, pr={pr}"
                )


# =====================================================================
# CATEGORY 6: p11 FEASIBLE INTERVAL
# =====================================================================

class TestP11FeasibleInterval:
    """The feasible p11 interval is [max(0, pe+pr-1), min(pe, pr)].
    Outside this interval, the joint distribution is infeasible."""

    @pytest.mark.parametrize("pe,pr,expected_lo,expected_hi", [
        (0.5, 0.1, 0.0, 0.1),    # pe + pr < 1, so lo = 0
        (0.6, 0.5, 0.1, 0.5),    # pe + pr > 1, so lo = pe+pr-1 = 0.1
        (0.7, 0.7, 0.4, 0.7),    # symmetric, lo = 2p - 1
        (0.0, 0.0, 0.0, 0.0),    # degenerate
        (1.0, 1.0, 1.0, 1.0),    # all YES
        (1.0, 0.0, 0.0, 0.0),    # engine always YES, retrieval always NO
    ])
    def test_feasible_interval_bounds(self, pe, pr, expected_lo, expected_hi):
        lo, hi = r4_1.feasible_p11_interval(pe, pr)
        assert abs(lo - expected_lo) < 1e-9, (
            f"lo wrong: got {lo}, expected {expected_lo}"
        )
        assert abs(hi - expected_hi) < 1e-9, (
            f"hi wrong: got {hi}, expected {expected_hi}"
        )

    def test_infeasible_p11_gives_zero_power(self):
        """If we pass an infeasible p11, power should be 0 (because
        the multinomial probabilities are zero)."""
        # pe=0.5, pr=0.1, feasible p11 in [0, 0.1].
        # p11 = 0.2 is infeasible (would require p01 = -0.1).
        p = r4_1.power_at_p11(0.5, 0.1, 0.2)
        assert p == 0.0


# =====================================================================
# CATEGORY 7: COMBINED RULE MATCHES PROTOCOL
# =====================================================================

class TestCombinedRuleMatchesProtocol:
    """The decision rule must be EXACTLY:
        p_one_sided < 0.05 AND ci_lower > 0.20

    No more, no less. The rule must match r4_reference_vectors.py
    exactly (single source of truth).
    """

    def test_passes_rule_uses_both_gates(self):
        """passes_combined_rule must return True iff BOTH conditions
        hold."""
        # (b=12, c=1) passes both: p=0.0017 < 0.05, CI_lower=0.267 > 0.20
        assert r4_1.passes_combined_rule(12, 1) is True
        # (b=9, c=1) fails CI gate: p=0.011 < 0.05, CI_lower=0.119 < 0.20
        assert r4_1.passes_combined_rule(9, 1) is False
        # (b=8, c=2) fails p gate: p=0.055 > 0.05, CI_lower=-0.006 < 0.20
        assert r4_1.passes_combined_rule(8, 2) is False
        # (b=14, c=0) passes both: p=6.1e-5 < 0.05, CI_lower=0.474 > 0.20
        assert r4_1.passes_combined_rule(14, 0) is True

    def test_passes_rule_matches_reference_vectors(self):
        """For each frozen reference vector, passes_combined_rule must
        return the same value as the committed vector's 'passes' field."""
        committed = json.loads(REFERENCE_VECTORS.read_text())
        for v in committed["vectors"]:
            actual = r4_1.passes_combined_rule(v["b"], v["c"])
            assert actual == v["passes"], (
                f"passes mismatch for (b={v['b']}, c={v['c']}): "
                f"script={actual}, committed={v['passes']}"
            )

    def test_combined_rule_type_i_upper_bound_holds(self):
        """Under H0 (pe = pr), the combined rule's Type-I error rate
        must be ≤ alpha = 0.05. The protocol claims:

            P(p < 0.05 AND CI_lower > 0.20 | H0) ≤ P(p < 0.05 | H0) ≤ 0.05

        This test verifies the claim mechanically across all null
        scenarios."""
        for pe, pr in r4_1.TYPE_I_SCENARIOS:
            row = r4_1.search_power_extrema(pe, pr)
            assert row["power_max"] <= 0.05 + 1e-9, (
                f"Type-I error exceeds alpha=0.05 for pe=pr={pe}: "
                f"max Type-I = {row['power_max']}"
            )


# =====================================================================
# CATEGORY 8: NO HANDWRITTEN POWER TABLE
# =====================================================================

class TestNoHandwrittenPowerTable:
    """The power table in r4_1_power_analysis.json must be generated
    by the script, not hand-written. This is verified by:

    1. The artifact exists (script must be run).
    2. The artifact's SHA-256 matches what the script produces now
       (no manual edits to the JSON).
    3. The artifact does NOT contain a 'handwritten' marker.
    """

    def test_artifact_exists(self):
        assert OUTPUT.exists(), (
            f"Power analysis artifact not found at {OUTPUT}. "
            f"Run scripts/r4_1_power_analysis.py to generate it."
        )

    def test_artifact_sha_matches_script_output(self):
        """Re-running the script must produce the same SHA-256. If it
        does not, the JSON was hand-edited after generation."""
        committed = json.loads(OUTPUT.read_text())
        committed_sha = committed.get("artifact_sha256")
        assert committed_sha is not None, (
            "artifact_sha256 field missing from committed JSON"
        )

        # Re-build the payload in-memory by re-running the script's
        # main logic. We don't re-write the file; we just compare.
        # The simplest check: re-compute the power for each scenario
        # and verify it matches the committed value.
        for row in committed["power_scenarios"]:
            pe, pr = row["pe"], row["pr"]
            actual = r4_1.search_power_extrema(pe, pr)
            assert abs(actual["power_min"] - row["power_min"]) < 1e-9, (
                f"power_min drift for pe={pe}, pr={pr}: "
                f"committed={row['power_min']}, recomputed={actual['power_min']}"
            )
            assert abs(actual["power_max"] - row["power_max"]) < 1e-9, (
                f"power_max drift for pe={pe}, pr={pr}: "
                f"committed={row['power_max']}, recomputed={actual['power_max']}"
            )

    def test_artifact_has_no_handwritten_marker(self):
        """The artifact must not contain any field indicating manual
        editing."""
        committed = json.loads(OUTPUT.read_text())
        for key in committed:
            assert "handwritten" not in key.lower(), (
                f"Artifact contains handwritten marker field: {key}"
            )
            assert "manual" not in key.lower(), (
                f"Artifact contains manual marker field: {key}"
            )

    def test_artifact_marks_r4_1_table_invalid(self):
        """The artifact's summary must explicitly note that the
        hand-written R4.1 table is INVALID. This prevents future
        readers from citing the wrong source."""
        committed = json.loads(OUTPUT.read_text())
        note = committed["summary"]["frozen_status_note"]
        assert "INVALID" in note, (
            "frozen_status_note must mark the R4.1 hand-written table "
            "as INVALID so readers do not cite it."
        )


# =====================================================================
# CATEGORY 9: AUDIT-NUMBER REPRODUCTION
# =====================================================================

class TestAuditNumberReproduction:
    """Reproduce the exact numbers from the external audit (round 35).

    The auditor independently evaluated the complete paired-multinomial
    distribution under the exact R4.1 decision rule and reported:

        | Engine | Retrieval | Actual minimum | Actual maximum |
        |   0.50 |      0.10 |          28.3% |          40.4% |
        |   0.50 |      0.05 |          46.3% |          58.6% |
        |   0.60 |      0.10 |          49.3% |          74.8% |
        |   0.60 |      0.05 |          69.7% |          86.9% |
        |   0.70 |      0.10 |          70.7% |          94.3% |

    This test class verifies the script reproduces those numbers
    mechanically. If any number drifts, the script has a regression.
    """

    @pytest.mark.parametrize("pe,pr,expected_min_pct,expected_max_pct", [
        (0.50, 0.10, 0.283, 0.404),
        (0.50, 0.05, 0.463, 0.586),
        (0.60, 0.10, 0.493, 0.748),
        (0.60, 0.05, 0.697, 0.869),
        (0.70, 0.10, 0.707, 0.943),
    ])
    def test_audit_numbers_reproduced(self, pe, pr,
                                       expected_min_pct, expected_max_pct):
        """The script's power_min and power_max must match the
        auditor's independent calculation to within 0.5 percentage
        points (rounding tolerance)."""
        row = r4_1.search_power_extrema(pe, pr)
        # The auditor rounded to 1 decimal place in percentage form,
        # so 28.3% means 0.283 ± 0.0005.
        assert abs(row["power_min"] - expected_min_pct) < 0.005, (
            f"power_min for pe={pe}, pr={pr}: "
            f"got {row['power_min']:.4f}, auditor reported {expected_min_pct:.4f}"
        )
        assert abs(row["power_max"] - expected_max_pct) < 0.005, (
            f"power_max for pe={pe}, pr={pr}: "
            f"got {row['power_max']:.4f}, auditor reported {expected_max_pct:.4f}"
        )

    def test_r4_1_claimed_worst_case_is_actually_best_case(self):
        """The R4.1 document claims that for pe=0.50, pr=0.10, the
        worst-case power is <1% (at p11 = min(pe, pr) = 0.1).

        Mechanically, p11 = 0.1 is where power is MAXIMIZED (40.4%),
        not minimized. The worst case is at p11 = 0 (28.3%).

        This is the central defect in R4.1: the worst-case and
        best-case labels are reversed."""
        pe, pr = 0.50, 0.10
        p11_worst_per_r41 = min(pe, pr)  # = 0.1
        p11_best_per_r41 = 0.0
        power_at_r41_worst = r4_1.power_at_p11(pe, pr, p11_worst_per_r41)
        power_at_r41_best = r4_1.power_at_p11(pe, pr, p11_best_per_r41)

        # R4.1 said power_at_p11=0.1 is <1%. Actually it's ~40%.
        assert power_at_r41_worst > 0.30, (
            f"R4.1 claimed power at p11=min(pe,pr) is <1%, but it is "
            f"actually {power_at_r41_worst:.4f}. The R4.1 'worst case' "
            f"label is wrong."
        )
        # R4.1 said power_at_p11=0 is 38%. Actually it's ~28%.
        # So the labels are reversed: p11=0 is WORSE than p11=0.1.
        assert power_at_r41_best < power_at_r41_worst, (
            f"R4.1 claimed p11=0 is the best case, but p11=0 "
            f"(power={power_at_r41_best:.4f}) is actually WORSE than "
            f"p11=0.1 (power={power_at_r41_worst:.4f}). The R4.1 "
            f"best/worst labels are reversed."
        )

    def test_r4_1_power_table_is_not_trustworthy(self):
        """The R4.1 document's power table is mechanically refuted.

        R4.1 claims (row 1): power worst <1%, power best 38%.
        Actual: power worst 28.3%, power best 40.4%.

        The R4.1 worst-case claim is off by a factor of ~28x. This
        test exists to prevent anyone from re-citing the R4.1 table
        without first reading this script's output."""
        row = r4_1.search_power_extrema(0.50, 0.10)
        # R4.1 claimed worst <1%.
        assert row["power_min"] > 0.20, (
            f"Actual power_min for theta=0.40 is {row['power_min']:.4f}, "
            f"which is >20x larger than R4.1's claimed worst case of <1%."
        )


# =====================================================================
# CATEGORY 10: STATISTICAL LESSON RECORDED
# =====================================================================

class TestStatisticalLessonRecorded:
    """The artifact must record the statistical lesson so future
    readers cannot repeat the mistake."""

    def test_artifact_records_lesson(self):
        committed = json.loads(OUTPUT.read_text())
        lesson = committed.get("statistical_lesson", "")
        assert "discordant-pair" in lesson.lower(), (
            "statistical_lesson must mention 'discordant-pair'"
        )
        assert "composite decision rule" in lesson.lower(), (
            "statistical_lesson must mention 'composite decision rule'"
        )
        assert "SIGN of (b - c)" in lesson, (
            "statistical_lesson must mention that power depends on the "
            "SIGN of (b - c), not just the count (b + c)"
        )
        assert "polynomial" in lesson.lower(), (
            "statistical_lesson (R4.1A) must mention that Power(p11) is "
            "a polynomial, enabling certified extrema via root-finding"
        )
        assert "CERTIFIED" in lesson, (
            "statistical_lesson (R4.1A) must mention that extrema are "
            "CERTIFIED, not merely approximated by a grid"
        )


# =====================================================================
# CATEGORY 11: POLYNOMIAL CONSTRUCTION CORRECTNESS
# =====================================================================

class TestPolynomialConstruction:
    """Verify that power_polynomial(pe, pr)(p11) matches the direct
    computation power_at_p11(pe, pr, p11) for all tested (pe, pr, p11).

    This is the foundational correctness test for the certified method.
    If the polynomial construction is wrong, every certified extremum
    is wrong. The grid-search cross-check in search_power_extrema
    catches gross errors, but this test catches them at a finer grain.
    """

    @pytest.mark.parametrize("pe,pr", [
        (0.50, 0.10), (0.50, 0.05), (0.60, 0.10), (0.60, 0.05),
        (0.70, 0.10), (0.40, 0.10), (0.30, 0.05), (0.20, 0.00),
        (0.10, 0.10), (0.50, 0.50), (0.70, 0.70),
    ])
    def test_polynomial_matches_direct_computation(self, pe, pr):
        """For several p11 values in the feasible interval, the
        polynomial-evaluated power must match the direct computation.

        Tolerance is 1e-6 (not 1e-9) because:
        1. The polynomial multiplies large multinomial coefficients
           (up to ~3.5M for N=20) in double precision, while the direct
           computation uses log-space (math.lgamma, math.exp).
        2. At boundary points (e.g., p11 = hi), pe - p11 can be a tiny
           negative number like -1.11e-16 (not exactly 0) due to binary
           floating-point representation. The direct computation clamps
           this to 0, but the polynomial evaluates it directly, producing
           a tiny residual ~1e-7.

        A tolerance of 1e-6 accommodates both effects while still being
        100x tighter than the 1e-4 grid-search agreement threshold used
        for certified extrema certification.
        """
        lo, hi = r4_1.feasible_p11_interval(pe, pr)
        poly = r4_1.power_polynomial(pe, pr)
        # Test at 11 points across the feasible interval.
        for i in range(11):
            p11 = lo + (hi - lo) * i / 10
            poly_val = float(poly(p11))
            direct_val = r4_1.power_at_p11(pe, pr, p11)
            assert abs(poly_val - direct_val) < 1e-6, (
                f"Polynomial mismatch at pe={pe}, pr={pr}, p11={p11}: "
                f"poly={poly_val:.12f}, direct={direct_val:.12f}, "
                f"diff={abs(poly_val - direct_val):.2e}"
            )

    def test_polynomial_matches_at_endpoints(self):
        """The polynomial must match direct computation at both
        endpoints of the feasible interval."""
        pe, pr = 0.50, 0.10
        lo, hi = r4_1.feasible_p11_interval(pe, pr)
        poly = r4_1.power_polynomial(pe, pr)
        assert abs(float(poly(lo)) - r4_1.power_at_p11(pe, pr, lo)) < 1e-6
        assert abs(float(poly(hi)) - r4_1.power_at_p11(pe, pr, hi)) < 1e-6

    def test_polynomial_matches_at_interior_extremum(self):
        """For pe=0.40, pr=0.10, the certified interior extremum is
        at p11 ≈ 0.0474. The polynomial must match direct computation
        at this exact point."""
        pe, pr = 0.40, 0.10
        poly = r4_1.power_polynomial(pe, pr)
        certified = r4_1.certified_extrema(pe, pr)
        # Find the interior stationary point
        assert certified["n_stationary_points"] >= 1, (
            "Expected at least 1 stationary point for pe=0.40, pr=0.10"
        )
        sp = certified["stationary_points"][0]["p11"]
        poly_val = float(poly(sp))
        direct_val = r4_1.power_at_p11(pe, pr, sp)
        assert abs(poly_val - direct_val) < 1e-6, (
            f"Polynomial mismatch at interior extremum p11={sp}: "
            f"poly={poly_val:.12f}, direct={direct_val:.12f}"
        )


# =====================================================================
# CATEGORY 12: CERTIFIED EXTREMA
# =====================================================================

class TestCertifiedExtrema:
    """Verify the certified polynomial-based extremum finder produces
    correct, global extrema that agree with the grid-search cross-check.

    This is the central R4.1A upgrade: extrema are CERTIFIED via
    polynomial root-finding, not merely approximated by a grid.
    """

    @pytest.mark.parametrize("pe,pr", r4_1.POWER_SCENARIOS + r4_1.TYPE_I_SCENARIOS)
    def test_certified_agrees_with_grid(self, pe, pr):
        """For every scenario, the certified and grid-search extrema
        must agree to within 1e-4. The search_power_extrema function
        raises AssertionError if they don't, so just calling it is
        sufficient."""
        row = r4_1.search_power_extrema(pe, pr)
        assert row["grid_and_certified_agree"] is True, (
            f"Certified and grid-search disagree for pe={pe}, pr={pr}"
        )
        assert abs(row["power_min"] - row["grid_search"]["power_min"]) < 1e-4
        assert abs(row["power_max"] - row["grid_search"]["power_max"]) < 1e-4

    @pytest.mark.parametrize("pe,pr", r4_1.POWER_SCENARIOS + r4_1.TYPE_I_SCENARIOS)
    def test_polynomial_degree_at_most_N(self, pe, pr):
        """The power polynomial must have degree <= N = 20. This is
        because each term P(b,c|p11) is a polynomial of degree
        b + c + (N-b-c) = N, and the sum of degree-N polynomials
        has degree <= N."""
        poly = r4_1.power_polynomial(pe, pr)
        # numpy Polynomial degree: len(coef) - 1, but trailing zeros
        # may be trimmed. The degree is poly.degree().
        assert poly.degree() <= r4_1.N, (
            f"Polynomial degree {poly.degree()} exceeds N={r4_1.N} "
            f"for pe={pe}, pr={pr}"
        )

    @pytest.mark.parametrize("pe,pr", r4_1.POWER_SCENARIOS)
    def test_stationary_points_in_feasible_interval(self, pe, pr):
        """Every stationary point reported by certified_extrema must
        lie in the feasible interval [lo, hi]."""
        lo, hi = r4_1.feasible_p11_interval(pe, pr)
        certified = r4_1.certified_extrema(pe, pr)
        for sp in certified["stationary_points"]:
            assert lo - 1e-9 <= sp["p11"] <= hi + 1e-9, (
                f"Stationary point p11={sp['p11']} outside feasible "
                f"interval [{lo}, {hi}] for pe={pe}, pr={pr}"
            )

    @pytest.mark.parametrize("pe,pr", r4_1.POWER_SCENARIOS + r4_1.TYPE_I_SCENARIOS)
    def test_certified_extrema_are_truly_global(self, pe, pr):
        """Verify that NO point in a very fine grid (5001 points)
        exceeds the certified power_max or is below the certified
        power_min. This is a stronger check than the 1001-point
        cross-check inside search_power_extrema.

        If the polynomial root-finding missed a stationary point, this
        test would catch it — the fine grid would find a power value
        outside the certified [min, max] range."""
        row = r4_1.search_power_extrema(pe, pr)
        lo, hi = r4_1.feasible_p11_interval(pe, pr)
        if hi <= lo + 1e-15:
            return  # degenerate interval
        # 5001 points — 5x denser than the internal cross-check.
        for i in range(5001):
            p11 = lo + (hi - lo) * i / 5000
            p = r4_1.power_at_p11(pe, pr, p11)
            assert p >= row["power_min"] - 1e-6, (
                f"Fine-grid power {p:.8f} at p11={p11} is below "
                f"certified power_min {row['power_min']:.8f} "
                f"for pe={pe}, pr={pr}. The certified method missed "
                f"a minimum."
            )
            assert p <= row["power_max"] + 1e-6, (
                f"Fine-grid power {p:.8f} at p11={p11} exceeds "
                f"certified power_max {row['power_max']:.8f} "
                f"for pe={pe}, pr={pr}. The certified method missed "
                f"a maximum."
            )

    def test_pe040_pr010_certified_interior_extremum(self):
        """For pe=0.40, pr=0.10, theta=0.30, the certified method must
        find at least 1 interior stationary point. The grid search
        approximated its location as p11 ≈ 0.0474; the certified
        method gives the exact location.

        This is the scenario that proves grid-only reasoning is
        insufficient — the extremum is in the interior, and its
        exact location matters."""
        certified = r4_1.certified_extrema(0.40, 0.10)
        assert certified["n_stationary_points"] >= 1, (
            f"Expected >= 1 stationary point for pe=0.40, pr=0.10, "
            f"got {certified['n_stationary_points']}"
        )
        # The stationary point must be in the interior (not at endpoints).
        lo, hi = r4_1.feasible_p11_interval(0.40, 0.10)
        sp = certified["stationary_points"][0]["p11"]
        assert lo < sp < hi, (
            f"Stationary point p11={sp} must be in the interior of "
            f"[{lo}, {hi}]"
        )
        # The certified argmax must match this stationary point.
        row = r4_1.search_power_extrema(0.40, 0.10)
        assert abs(row["p11_at_max"] - sp) < 1e-9, (
            f"Certified argmax p11={row['p11_at_max']} must match "
            f"the interior stationary point p11={sp}"
        )

    def test_artifact_records_stationary_points(self):
        """The committed JSON must record the stationary points for
        each scenario, so the certification is auditable."""
        committed = json.loads(OUTPUT.read_text())
        for row in committed["power_scenarios"]:
            assert "stationary_points" in row, (
                f"Scenario pe={row['pe']}, pr={row['pr']} missing "
                f"stationary_points field"
            )
            assert "n_stationary_points" in row, (
                f"Scenario pe={row['pe']}, pr={row['pr']} missing "
                f"n_stationary_points field"
            )

    def test_artifact_records_grid_cross_check(self):
        """The committed JSON must record the grid-search cross-check
        values alongside the certified values."""
        committed = json.loads(OUTPUT.read_text())
        for row in committed["power_scenarios"]:
            assert "grid_search" in row, (
                f"Scenario pe={row['pe']}, pr={row['pr']} missing "
                f"grid_search cross-check field"
            )
            gs = row["grid_search"]
            for key in ("power_min", "power_max", "p11_at_min",
                        "p11_at_max", "grid_size"):
                assert key in gs, (
                    f"grid_search missing key '{key}' for "
                    f"pe={row['pe']}, pr={row['pr']}"
                )
            assert row["grid_and_certified_agree"] is True, (
                f"Certified and grid disagree for pe={row['pe']}, "
                f"pr={row['pr']}"
            )


# =====================================================================
# CATEGORY 13: TYPE-I REPORTING DISTINCTION
# =====================================================================

class TestTypeIReportingDistinction:
    """The artifact must distinguish:
    A. max_type_i_among_evaluated_null_scenarios (exploratory, finite set)
    B. global_type_i_upper_bound (rigorous, = alpha = 0.05)

    Per audit round 36:
        "If the current script only evaluates a finite collection of
         null scenarios, then 'max Type-I = 0.0059' should NOT be
         written as the global Type-I operating characteristic."

    The global maximum over the continuous null space
    (pe = pr = p, p in [0, 1]) is NOT established. Only the universal
    upper bound (0.05) is claimed.
    """

    def test_artifact_has_tested_scenario_max(self):
        """The artifact must report the max over tested null scenarios
        as a distinct field, NOT as 'global max'."""
        committed = json.loads(OUTPUT.read_text())
        summary = committed["summary"]
        assert "max_type_i_among_evaluated_null_scenarios" in summary, (
            "Artifact must have 'max_type_i_among_evaluated_null_scenarios' "
            "field (not the old 'max_type_i_across_nulls')"
        )
        # The OLD field name must NOT exist.
        assert "max_type_i_across_nulls" not in summary, (
            "Artifact must NOT use the old field name "
            "'max_type_i_across_nulls' — it was renamed to "
            "'max_type_i_among_evaluated_null_scenarios' to avoid "
            "implying it is a global bound."
        )

    def test_artifact_has_global_upper_bound(self):
        """The artifact must report the global Type-I upper bound
        (= alpha = 0.05) as a distinct field."""
        committed = json.loads(OUTPUT.read_text())
        summary = committed["summary"]
        assert "global_type_i_upper_bound" in summary, (
            "Artifact must have 'global_type_i_upper_bound' field"
        )
        assert summary["global_type_i_upper_bound"] == r4_1.ALPHA, (
            f"global_type_i_upper_bound must equal alpha={r4_1.ALPHA}, "
            f"got {summary['global_type_i_upper_bound']}"
        )

    def test_tested_max_is_below_global_bound(self):
        """The tested-scenario max must be <= the global upper bound.
        This is expected because the global bound (0.05) is a rigorous
        universal inequality, and the tested scenarios are a subset."""
        committed = json.loads(OUTPUT.read_text())
        summary = committed["summary"]
        tested_max = summary["max_type_i_among_evaluated_null_scenarios"]
        global_bound = summary["global_type_i_upper_bound"]
        assert tested_max <= global_bound + 1e-9, (
            f"Tested-scenario max ({tested_max}) exceeds global bound "
            f"({global_bound}). This should never happen — the global "
            f"bound is a universal inequality."
        )

    def test_tested_max_note_explains_it_is_not_global(self):
        """The artifact must include a note explaining that the
        tested-scenario max is NOT a global bound."""
        committed = json.loads(OUTPUT.read_text())
        summary = committed["summary"]
        note = summary.get("max_type_i_among_evaluated_null_scenarios_note", "")
        assert "NOT a global bound" in note or "not" in note.lower(), (
            "The tested-scenario max note must explicitly state that "
            "it is NOT a global bound."
        )

    def test_global_bound_note_exclaims_rigorous_origin(self):
        """The artifact must include a note explaining that the global
        upper bound comes from P(combined) <= P(p<0.05) <= alpha."""
        committed = json.loads(OUTPUT.read_text())
        summary = committed["summary"]
        note = summary.get("global_type_i_upper_bound_note", "")
        assert "P(p" in note or "P(combined" in note, (
            "The global bound note must explain the rigorous origin: "
            "P(combined) <= P(p<0.05) <= alpha."
        )
        assert "NOT established" in note or "not established" in note.lower(), (
            "The global bound note must state that the global max over "
            "the continuous null space is NOT established."
        )

    def test_artifact_does_not_claim_global_max_is_0_0059(self):
        """The artifact must NOT claim that 0.0059 is the global Type-I
        maximum. This was the specific overclaim flagged in audit
        round 36."""
        committed = json.loads(OUTPUT.read_text())
        summary = committed["summary"]
        tested_max = summary["max_type_i_among_evaluated_null_scenarios"]
        # The field name itself must not imply globality.
        assert "global" not in "max_type_i_among_evaluated_null_scenarios".lower(), (
            "The tested-scenario max field name must not contain 'global'."
        )
        # The global field must be alpha, not 0.0059.
        assert summary["global_type_i_upper_bound"] == 0.05, (
            "The global upper bound must be 0.05 (alpha), not the "
            "tested-scenario max."
        )
