"""Tests: R4.1 Power Analysis — exact joint-distribution enumerator.

Per audit round 35 (R4.1 freeze-block audit):

    "Minimizing discordant-pair count does not necessarily minimize
     power for a composite decision rule. Power must be evaluated over
     the complete joint outcome distribution and the complete
     preregistered decision function."

    "The R4.1 document contains numerical power claims that I cannot
     reproduce from a committed power-analysis implementation."

    "Build the statistical engine first. Do not write R4.2 first."

Test categories:
    1. Probability mass conservation — sum over all (b, c) = 1.0
    2. Joint distribution constraints — p10 + p11 = pe, p01 + p11 = pr
    3. Power range — power ∈ [0, 1] for every scenario
    4. Reference vector cross-check — script uses the SAME estimator
       as r4_reference_vectors.py (no drift)
    5. Extrema are actual min/max — search the interior, not just
       endpoints (the central statistical correction)
    6. p11 feasible interval — bounds are correct
    7. Combined rule matches protocol — passes == (p<0.05 AND CI>0.20)
    8. No handwritten power table — JSON is generated by the script
    9. Audit-number reproduction — match the values the external
       auditor independently calculated
"""
import json
import importlib.util
import math
import sys
from pathlib import Path

import pytest
from scipy.stats import binom

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))

# Import the power analysis module.
spec = importlib.util.spec_from_file_location(
    "r4_1_power_analysis",
    REPO / "scripts" / "r4_1_power_analysis.py",
)
r4_1 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(r4_1)

OUTPUT = (
    REPO / "experiments" / "measurement_discrimination"
    / "r4_1_power_analysis.json"
)
REFERENCE_VECTORS = (
    REPO / "experiments" / "measurement_discrimination"
    / "r4_reference_vectors.json"
)


# =====================================================================
# CATEGORY 1: PROBABILITY MASS CONSERVATION
# =====================================================================

class TestProbabilityMassConservation:
    """The multinomial marginal over (b, c) must sum to 1.0 for every
    admissible (p10, p01) pair. If it does not, the enumerator is
    missing outcomes and every power calculation is wrong."""

    @pytest.mark.parametrize("p10,p01", [
        (0.5, 0.1),    # R4.1 row 1 at p11=0
        (0.4, 0.0),    # R4.1 row 1 at p11=0.1
        (0.6, 0.05),
        (0.3, 0.0),
        (0.1, 0.1),    # symmetric
        (0.0, 0.0),    # degenerate: all concordant
        (0.5, 0.5),    # degenerate: no concordant
    ])
    def test_probability_mass_equals_one(self, p10, p01):
        """sum_{b, c : b+c <= N} P(b, c) must equal 1.0."""
        if p10 + p01 > 1.0 + 1e-12:
            pytest.skip("infeasible probability combination")
        total = sum(
            r4_1.multinomial_pmf_b_c(b, c, p10, p01, r4_1.N)
            for b in range(r4_1.N + 1)
            for c in range(r4_1.N + 1 - b)
        )
        assert abs(total - 1.0) < 1e-9, (
            f"Probability mass does not sum to 1.0 for "
            f"(p10={p10}, p01={p01}): got {total}"
        )

    def test_probability_mass_one_at_degenerate_p11(self):
        """When p11 = min(pe, pr) = pr (so p01 = 0), all discordant
        mass is on (b, 0). The sum over (b, 0) must equal
        sum_{b=0}^{N} Binom(N, p10) = 1.0."""
        pe, pr = 0.5, 0.1
        p11 = min(pe, pr)  # = 0.1
        p10 = pe - p11     # = 0.4
        p01 = pr - p11     # = 0.0
        total = sum(
            r4_1.multinomial_pmf_b_c(b, 0, p10, p01, r4_1.N)
            for b in range(r4_1.N + 1)
        )
        assert abs(total - 1.0) < 1e-9


# =====================================================================
# CATEGORY 2: JOINT DISTRIBUTION CONSTRAINTS
# =====================================================================

class TestJointDistributionConstraints:
    """The marginal-probability constraints p10 + p11 = pe and
    p01 + p11 = pr must hold for every admissible p11."""

    @pytest.mark.parametrize("pe,pr", [
        (0.5, 0.1), (0.6, 0.05), (0.7, 0.1), (0.3, 0.05),
    ])
    def test_marginal_constraints_hold(self, pe, pr):
        lo, hi = r4_1.feasible_p11_interval(pe, pr)
        # Sample several p11 values in the interior.
        for i in range(11):
            p11 = lo + (hi - lo) * i / 10
            p00, p01, p10, p11_actual = r4_1.joint_from_p11(pe, pr, p11)
            assert abs((p10 + p11_actual) - pe) < 1e-9, (
                f"p10 + p11 != pe: {p10} + {p11_actual} != {pe}"
            )
            assert abs((p01 + p11_actual) - pr) < 1e-9, (
                f"p01 + p11 != pr: {p01} + {p11_actual} != {pr}"
            )
            assert abs((p00 + p01 + p10 + p11_actual) - 1.0) < 1e-9, (
                f"Probabilities do not sum to 1: "
                f"{p00} + {p01} + {p10} + {p11_actual} = "
                f"{p00 + p01 + p10 + p11_actual}"
            )
            assert p00 >= -1e-12, f"p00 < 0: {p00}"
            assert p01 >= -1e-12, f"p01 < 0: {p01}"
            assert p10 >= -1e-12, f"p10 < 0: {p10}"
            assert p11_actual >= -1e-12, f"p11 < 0: {p11_actual}"


# =====================================================================
# CATEGORY 3: POWER RANGE
# =====================================================================

class TestPowerRange:
    """Power is a probability and must lie in [0, 1]."""

    @pytest.mark.parametrize("pe,pr", r4_1.POWER_SCENARIOS + r4_1.TYPE_I_SCENARIOS)
    def test_power_between_zero_and_one(self, pe, pr):
        row = r4_1.search_power_extrema(pe, pr)
        assert 0.0 <= row["power_min"] <= 1.0, (
            f"power_min out of [0,1]: {row['power_min']}"
        )
        assert 0.0 <= row["power_max"] <= 1.0, (
            f"power_max out of [0,1]: {row['power_max']}"
        )
        assert row["power_min"] <= row["power_max"] + 1e-9, (
            f"power_min > power_max: {row['power_min']} > {row['power_max']}"
        )

    def test_power_at_null_is_zero_when_peq_zero(self):
        """If pe = pr = 0, every outcome is (b=0, c=0, n_d=0).
        passes(0, 0) = (1.0 < 0.05) AND (CI_lower > 0.20) = False.
        Power = 0."""
        row = r4_1.search_power_extrema(0.0, 0.0)
        assert row["power_min"] == 0.0
        assert row["power_max"] == 0.0


# =====================================================================
# CATEGORY 4: REFERENCE VECTOR CROSS-CHECK
# =====================================================================

class TestReferenceVectorsMatch:
    """The power script must use the SAME estimator as
    r4_reference_vectors.py. Drift between the two would silently
    invalidate every power number."""

    def test_estimator_imported_not_reimplemented(self):
        """mcnemar_analysis must be sourced from
        r4_reference_vectors.py, not re-implemented in the power
        script. We verify by checking that the function source code
        is identical in both modules — a stronger guarantee than
        object identity, which fails because importlib creates fresh
        module objects on each load."""
        import inspect
        spec_rv = importlib.util.spec_from_file_location(
            "r4_reference_vectors",
            REPO / "scripts" / "r4_reference_vectors.py",
        )
        rv = importlib.util.module_from_spec(spec_rv)
        spec_rv.loader.exec_module(rv)
        src_in_power = inspect.getsource(r4_1.mcnemar_analysis)
        src_in_reference = inspect.getsource(rv.mcnemar_analysis)
        assert src_in_power == src_in_reference, (
            "mcnemar_analysis source code differs between "
            "r4_1_power_analysis.py and r4_reference_vectors.py. "
            "The power script must use the SAME estimator — single "
            "source of truth."
        )
        # Additionally, verify the power script does NOT define its
        # own mcnemar_analysis (it should only import it).
        power_src = (REPO / "scripts" / "r4_1_power_analysis.py").read_text()
        # The script should not contain a 'def mcnemar_analysis' line.
        assert "def mcnemar_analysis" not in power_src, (
            "r4_1_power_analysis.py contains 'def mcnemar_analysis' — "
            "the estimator must be IMPORTED, not re-defined."
        )

    @pytest.mark.parametrize("b,c", [(9, 1), (12, 1), (8, 2), (14, 0)])
    def test_individual_vectors_match_committed(self, b, c):
        """Each frozen vector must match the committed JSON exactly."""
        committed = json.loads(REFERENCE_VECTORS.read_text())
        committed_vec = next(
            v for v in committed["vectors"] if v["b"] == b and v["c"] == c
        )
        actual = r4_1.mcnemar_analysis(b, c, r4_1.N)
        for key in ("b", "c", "N", "n_d", "theta_hat",
                    "p_one_sided", "ci_lower", "ci_upper", "passes"):
            assert actual[key] == committed_vec[key], (
                f"Mismatch on (b={b}, c={c}) key '{key}': "
                f"script={actual[key]!r}, committed={committed_vec[key]!r}"
            )

    def test_cross_check_function_runs_clean(self):
        """The cross-check function in the script must pass without
        raising. This is the function the main script calls before
        generating the JSON."""
        assert r4_1.cross_check_reference_vectors() is True


# =====================================================================
# CATEGORY 5: EXTREMA ARE ACTUAL MIN/MAX
# =====================================================================

class TestExtremaAreActualMinMax:
    """The central statistical correction: extrema are NOT assumed to
    occur at endpoints. The script must search the interior.

    This is the test that catches the R4.1 defect: R4.1 assumed
    p11 = min(pe, pr) gives the worst case and p11 = 0 gives the best
    case. That assumption is invalid for the combined decision rule.
    """

    def test_search_uses_dense_grid(self):
        """The script must evaluate power at > 2 points (not just
        endpoints). A grid of P11_GRID_SIZE = 1001 is used."""
        assert r4_1.P11_GRID_SIZE > 100, (
            "Grid must be dense (>100 points), not just endpoints."
        )

    def test_pe040_pr010_max_is_at_interior(self):
        """For pe=0.40, pr=0.10, theta=0.30, the power maximum is at
        an INTERIOR point of the feasible p11 interval, not at an
        endpoint. This is direct mechanical proof that endpoint-only
        reasoning is invalid.

        Reproduction: at the time of writing, the argmax p11 ≈ 0.0474,
        which is in the interior of [0, 0.1]."""
        row = r4_1.search_power_extrema(0.40, 0.10)
        assert row["p11_lo"] < row["p11_at_max"] < row["p11_hi"], (
            f"For pe=0.40, pr=0.10, the power MAXIMUM must be at an "
            f"interior point. Got p11_at_max={row['p11_at_max']} "
            f"in [{row['p11_lo']}, {row['p11_hi']}]."
        )

    def test_pe050_pr010_min_is_at_p11_zero_not_at_min(self):
        """For pe=0.50, pr=0.10, theta=0.40 (the FIRST row of R4.1's
        table), R4.1 claimed the worst case is at p11 = min(pe, pr) = 0.1.

        Mechanically, the worst case is at p11 = 0, NOT at p11 = 0.1.
        This is the row that 'is enough to kill the freeze' per the
        external audit."""
        row = r4_1.search_power_extrema(0.50, 0.10)
        assert row["p11_at_min"] == 0.0, (
            f"For pe=0.50, pr=0.10, the power MINIMUM is at p11=0 "
            f"(not at p11=min(pe,pr)=0.1 as R4.1 claimed). "
            f"Got p11_at_min={row['p11_at_min']}."
        )
        assert row["p11_at_max"] == 0.1, (
            f"For pe=0.50, pr=0.10, the power MAXIMUM is at p11=0.1 "
            f"(which R4.1 thought was the WORST case). "
            f"Got p11_at_max={row['p11_at_max']}."
        )

    def test_extrema_are_global_not_local(self):
        """For each scenario, verify that no point on the grid gives
        power below power_min or above power_max. This catches
        off-by-one errors in the argmin/argmax search."""
        for pe, pr in r4_1.POWER_SCENARIOS:
            row = r4_1.search_power_extrema(pe, pr)
            lo, hi = r4_1.feasible_p11_interval(pe, pr)
            # Re-evaluate at 50 random-ish points across the interval.
            for i in range(50):
                p11 = lo + (hi - lo) * i / 49
                p = r4_1.power_at_p11(pe, pr, p11)
                assert p >= row["power_min"] - 1e-9, (
                    f"Found power {p} below reported power_min "
                    f"{row['power_min']} at p11={p11} for "
                    f"pe={pe}, pr={pr}"
                )
                assert p <= row["power_max"] + 1e-9, (
                    f"Found power {p} above reported power_max "
                    f"{row['power_max']} at p11={p11} for "
                    f"pe={pe}, pr={pr}"
                )


# =====================================================================
# CATEGORY 6: p11 FEASIBLE INTERVAL
# =====================================================================

class TestP11FeasibleInterval:
    """The feasible p11 interval is [max(0, pe+pr-1), min(pe, pr)].
    Outside this interval, the joint distribution is infeasible."""

    @pytest.mark.parametrize("pe,pr,expected_lo,expected_hi", [
        (0.5, 0.1, 0.0, 0.1),    # pe + pr < 1, so lo = 0
        (0.6, 0.5, 0.1, 0.5),    # pe + pr > 1, so lo = pe+pr-1 = 0.1
        (0.7, 0.7, 0.4, 0.7),    # symmetric, lo = 2p - 1
        (0.0, 0.0, 0.0, 0.0),    # degenerate
        (1.0, 1.0, 1.0, 1.0),    # all YES
        (1.0, 0.0, 0.0, 0.0),    # engine always YES, retrieval always NO
    ])
    def test_feasible_interval_bounds(self, pe, pr, expected_lo, expected_hi):
        lo, hi = r4_1.feasible_p11_interval(pe, pr)
        assert abs(lo - expected_lo) < 1e-9, (
            f"lo wrong: got {lo}, expected {expected_lo}"
        )
        assert abs(hi - expected_hi) < 1e-9, (
            f"hi wrong: got {hi}, expected {expected_hi}"
        )

    def test_infeasible_p11_gives_zero_power(self):
        """If we pass an infeasible p11, power should be 0 (because
        the multinomial probabilities are zero)."""
        # pe=0.5, pr=0.1, feasible p11 in [0, 0.1].
        # p11 = 0.2 is infeasible (would require p01 = -0.1).
        p = r4_1.power_at_p11(0.5, 0.1, 0.2)
        assert p == 0.0


# =====================================================================
# CATEGORY 7: COMBINED RULE MATCHES PROTOCOL
# =====================================================================

class TestCombinedRuleMatchesProtocol:
    """The decision rule must be EXACTLY:
        p_one_sided < 0.05 AND ci_lower > 0.20

    No more, no less. The rule must match r4_reference_vectors.py
    exactly (single source of truth).
    """

    def test_passes_rule_uses_both_gates(self):
        """passes_combined_rule must return True iff BOTH conditions
        hold."""
        # (b=12, c=1) passes both: p=0.0017 < 0.05, CI_lower=0.267 > 0.20
        assert r4_1.passes_combined_rule(12, 1) is True
        # (b=9, c=1) fails CI gate: p=0.011 < 0.05, CI_lower=0.119 < 0.20
        assert r4_1.passes_combined_rule(9, 1) is False
        # (b=8, c=2) fails p gate: p=0.055 > 0.05, CI_lower=-0.006 < 0.20
        assert r4_1.passes_combined_rule(8, 2) is False
        # (b=14, c=0) passes both: p=6.1e-5 < 0.05, CI_lower=0.474 > 0.20
        assert r4_1.passes_combined_rule(14, 0) is True

    def test_passes_rule_matches_reference_vectors(self):
        """For each frozen reference vector, passes_combined_rule must
        return the same value as the committed vector's 'passes' field."""
        committed = json.loads(REFERENCE_VECTORS.read_text())
        for v in committed["vectors"]:
            actual = r4_1.passes_combined_rule(v["b"], v["c"])
            assert actual == v["passes"], (
                f"passes mismatch for (b={v['b']}, c={v['c']}): "
                f"script={actual}, committed={v['passes']}"
            )

    def test_combined_rule_type_i_upper_bound_holds(self):
        """Under H0 (pe = pr), the combined rule's Type-I error rate
        must be ≤ alpha = 0.05. The protocol claims:

            P(p < 0.05 AND CI_lower > 0.20 | H0) ≤ P(p < 0.05 | H0) ≤ 0.05

        This test verifies the claim mechanically across all null
        scenarios."""
        for pe, pr in r4_1.TYPE_I_SCENARIOS:
            row = r4_1.search_power_extrema(pe, pr)
            assert row["power_max"] <= 0.05 + 1e-9, (
                f"Type-I error exceeds alpha=0.05 for pe=pr={pe}: "
                f"max Type-I = {row['power_max']}"
            )


# =====================================================================
# CATEGORY 8: NO HANDWRITTEN POWER TABLE
# =====================================================================

class TestNoHandwrittenPowerTable:
    """The power table in r4_1_power_analysis.json must be generated
    by the script, not hand-written. This is verified by:

    1. The artifact exists (script must be run).
    2. The artifact's SHA-256 matches what the script produces now
       (no manual edits to the JSON).
    3. The artifact does NOT contain a 'handwritten' marker.
    """

    def test_artifact_exists(self):
        assert OUTPUT.exists(), (
            f"Power analysis artifact not found at {OUTPUT}. "
            f"Run scripts/r4_1_power_analysis.py to generate it."
        )

    def test_artifact_sha_matches_script_output(self):
        """Re-running the script must produce the same SHA-256. If it
        does not, the JSON was hand-edited after generation."""
        committed = json.loads(OUTPUT.read_text())
        committed_sha = committed.get("artifact_sha256")
        assert committed_sha is not None, (
            "artifact_sha256 field missing from committed JSON"
        )

        # Re-build the payload in-memory by re-running the script's
        # main logic. We don't re-write the file; we just compare.
        # The simplest check: re-compute the power for each scenario
        # and verify it matches the committed value.
        for row in committed["power_scenarios"]:
            pe, pr = row["pe"], row["pr"]
            actual = r4_1.search_power_extrema(pe, pr)
            assert abs(actual["power_min"] - row["power_min"]) < 1e-9, (
                f"power_min drift for pe={pe}, pr={pr}: "
                f"committed={row['power_min']}, recomputed={actual['power_min']}"
            )
            assert abs(actual["power_max"] - row["power_max"]) < 1e-9, (
                f"power_max drift for pe={pe}, pr={pr}: "
                f"committed={row['power_max']}, recomputed={actual['power_max']}"
            )

    def test_artifact_has_no_handwritten_marker(self):
        """The artifact must not contain any field indicating manual
        editing."""
        committed = json.loads(OUTPUT.read_text())
        for key in committed:
            assert "handwritten" not in key.lower(), (
                f"Artifact contains handwritten marker field: {key}"
            )
            assert "manual" not in key.lower(), (
                f"Artifact contains manual marker field: {key}"
            )

    def test_artifact_marks_r4_1_table_invalid(self):
        """The artifact's summary must explicitly note that the
        hand-written R4.1 table is INVALID. This prevents future
        readers from citing the wrong source."""
        committed = json.loads(OUTPUT.read_text())
        note = committed["summary"]["frozen_status_note"]
        assert "INVALID" in note, (
            "frozen_status_note must mark the R4.1 hand-written table "
            "as INVALID so readers do not cite it."
        )


# =====================================================================
# CATEGORY 9: AUDIT-NUMBER REPRODUCTION
# =====================================================================

class TestAuditNumberReproduction:
    """Reproduce the exact numbers from the external audit (round 35).

    The auditor independently evaluated the complete paired-multinomial
    distribution under the exact R4.1 decision rule and reported:

        | Engine | Retrieval | Actual minimum | Actual maximum |
        |   0.50 |      0.10 |          28.3% |          40.4% |
        |   0.50 |      0.05 |          46.3% |          58.6% |
        |   0.60 |      0.10 |          49.3% |          74.8% |
        |   0.60 |      0.05 |          69.7% |          86.9% |
        |   0.70 |      0.10 |          70.7% |          94.3% |

    This test class verifies the script reproduces those numbers
    mechanically. If any number drifts, the script has a regression.
    """

    @pytest.mark.parametrize("pe,pr,expected_min_pct,expected_max_pct", [
        (0.50, 0.10, 0.283, 0.404),
        (0.50, 0.05, 0.463, 0.586),
        (0.60, 0.10, 0.493, 0.748),
        (0.60, 0.05, 0.697, 0.869),
        (0.70, 0.10, 0.707, 0.943),
    ])
    def test_audit_numbers_reproduced(self, pe, pr,
                                       expected_min_pct, expected_max_pct):
        """The script's power_min and power_max must match the
        auditor's independent calculation to within 0.5 percentage
        points (rounding tolerance)."""
        row = r4_1.search_power_extrema(pe, pr)
        # The auditor rounded to 1 decimal place in percentage form,
        # so 28.3% means 0.283 ± 0.0005.
        assert abs(row["power_min"] - expected_min_pct) < 0.005, (
            f"power_min for pe={pe}, pr={pr}: "
            f"got {row['power_min']:.4f}, auditor reported {expected_min_pct:.4f}"
        )
        assert abs(row["power_max"] - expected_max_pct) < 0.005, (
            f"power_max for pe={pe}, pr={pr}: "
            f"got {row['power_max']:.4f}, auditor reported {expected_max_pct:.4f}"
        )

    def test_r4_1_claimed_worst_case_is_actually_best_case(self):
        """The R4.1 document claims that for pe=0.50, pr=0.10, the
        worst-case power is <1% (at p11 = min(pe, pr) = 0.1).

        Mechanically, p11 = 0.1 is where power is MAXIMIZED (40.4%),
        not minimized. The worst case is at p11 = 0 (28.3%).

        This is the central defect in R4.1: the worst-case and
        best-case labels are reversed."""
        pe, pr = 0.50, 0.10
        p11_worst_per_r41 = min(pe, pr)  # = 0.1
        p11_best_per_r41 = 0.0
        power_at_r41_worst = r4_1.power_at_p11(pe, pr, p11_worst_per_r41)
        power_at_r41_best = r4_1.power_at_p11(pe, pr, p11_best_per_r41)

        # R4.1 said power_at_p11=0.1 is <1%. Actually it's ~40%.
        assert power_at_r41_worst > 0.30, (
            f"R4.1 claimed power at p11=min(pe,pr) is <1%, but it is "
            f"actually {power_at_r41_worst:.4f}. The R4.1 'worst case' "
            f"label is wrong."
        )
        # R4.1 said power_at_p11=0 is 38%. Actually it's ~28%.
        # So the labels are reversed: p11=0 is WORSE than p11=0.1.
        assert power_at_r41_best < power_at_r41_worst, (
            f"R4.1 claimed p11=0 is the best case, but p11=0 "
            f"(power={power_at_r41_best:.4f}) is actually WORSE than "
            f"p11=0.1 (power={power_at_r41_worst:.4f}). The R4.1 "
            f"best/worst labels are reversed."
        )

    def test_r4_1_power_table_is_not_trustworthy(self):
        """The R4.1 document's power table is mechanically refuted.

        R4.1 claims (row 1): power worst <1%, power best 38%.
        Actual: power worst 28.3%, power best 40.4%.

        The R4.1 worst-case claim is off by a factor of ~28x. This
        test exists to prevent anyone from re-citing the R4.1 table
        without first reading this script's output."""
        row = r4_1.search_power_extrema(0.50, 0.10)
        # R4.1 claimed worst <1%.
        assert row["power_min"] > 0.20, (
            f"Actual power_min for theta=0.40 is {row['power_min']:.4f}, "
            f"which is >20x larger than R4.1's claimed worst case of <1%."
        )


# =====================================================================
# CATEGORY 10: STATISTICAL LESSON RECORDED
# =====================================================================

class TestStatisticalLessonRecorded:
    """The artifact must record the statistical lesson so future
    readers cannot repeat the mistake."""

    def test_artifact_records_lesson(self):
        committed = json.loads(OUTPUT.read_text())
        lesson = committed.get("statistical_lesson", "")
        assert "discordant-pair" in lesson.lower(), (
            "statistical_lesson must mention 'discordant-pair'"
        )
        assert "composite decision rule" in lesson.lower(), (
            "statistical_lesson must mention 'composite decision rule'"
        )
        assert "SIGN of (b - c)" in lesson, (
            "statistical_lesson must mention that power depends on the "
            "SIGN of (b - c), not just the count (b + c)"
        )
