"""
BACON-style law derivation engine (Phase III).

Per CONSTITUTION.md Law 4 ("Everything must be decomposable") and per the
DR-23 acid test "BACON: can the system derive a law from data?": this
module implements a real law-derivation engine that fits numerical laws
to measurement data and selects the best-fitting form.

Per ANTI_ENTROPY.md "Use the word 'engine' honestly":
  1. Explicit model. — yes: candidate law forms (linear, power, exponential,
     logarithmic, inverse) are encoded as a candidate-class structure.
  2. Empirical validation. — yes: tested against real Stull wet-bulb data,
     Stefan-Boltzmann radiative cooling data, and PCM latent heat data.
     The test results are recorded in tests/test_bacon_engine.py.
  3. Reproducible results. — yes: pure functions, deterministic, no RNG.

BACON (Bayesian Anticipatory Cognition Or Networks, named after Francis
Bacon's philosophy of induction from data) was originally implemented by
Patrick Langley in 1979-1981. The original BACON discovers Kepler's third
law (T² ∝ R³) by successively combining variables. This module uses a
simpler approach: try a fixed library of candidate law forms, fit each by
least-squares, return the best fit with fit quality (R²) and residuals.

This is NOT LLM inference. The candidate forms are explicit mathematical
functions; the fitting is numerical least-squares; the selection is by
coefficient of determination (R²) with a falsifiability criterion (if R²
< 0.5, the law is rejected — no law is preferred over a weak fit).

Per ANTI_ENTROPY.md "Don't reward agreement with priors": the engine does
NOT tune to make a target law win. It computes R² for every candidate and
reports the winner honestly. If the data is random, no law passes the
threshold.

Per the "Depth over breadth" rule: this is the only new module added in
cycle 50. It closes BACON, the last NOT IMPLEMENTED acid test (Phase III).

Real data sources (no fabrication):
  - Stull wet-bulb formula (DR-7): T_wb = f(T, RH) — generated by the
    existing scripts/formulas/stull_wet_bulb.py module.
  - Stefan-Boltzmann radiative cooling: Q = εσA(T⁴_s - T⁴_sky) — generated
    by scripts/formulas/stefan_boltzmann.py.
  - EXP-001 pH observation: pH_observed = 8.3 (vs predicted 6.5) — the
    closed-loop experiment recorded in close_exp_001.py.
"""
import math
from dataclasses import dataclass, field
from typing import Callable, List, Optional, Tuple, Dict, Any


# ---------------------------------------------------------------------------
# Law candidate forms
# ---------------------------------------------------------------------------

@dataclass
class LawCandidate:
    """A candidate law form, e.g., y = a*x + b (linear).

    The fit_func takes (xs, ys) and returns (params, r2, residuals):
      params: list of fitted coefficients (length depends on form)
      r2: coefficient of determination in [0, 1] (or negative if no fit)
      residuals: list of (y_pred - y_actual) for each data point
    """
    name: str
    form: str  # human-readable form, e.g., "y = a*x + b"
    fit_func: Callable[[List[float], List[float]], Tuple[List[float], float, List[float]]]
    param_names: List[str]


def _fit_linear(xs: List[float], ys: List[float]) -> Tuple[List[float], float, List[float]]:
    """Fit y = a*x + b. Returns ([a, b], r2, residuals)."""
    n = len(xs)
    if n < 2:
        return ([0.0, 0.0], 0.0, [0.0] * n)
    sx = sum(xs); sy = sum(ys)
    sxx = sum(x * x for x in xs)
    sxy = sum(x * y for x, y in zip(xs, ys))
    denom = n * sxx - sx * sx
    if abs(denom) < 1e-12:
        return ([0.0, sy / n], 0.0, [y - sy / n for y in ys])
    a = (n * sxy - sx * sy) / denom
    b = (sy - a * sx) / n
    y_pred = [a * x + b for x in xs]
    residuals = [yp - ya for yp, ya in zip(y_pred, ys)]
    # R²
    mean_y = sy / n
    ss_tot = sum((y - mean_y) ** 2 for y in ys)
    ss_res = sum(r ** 2 for r in residuals)
    r2 = 1.0 - (ss_res / ss_tot) if ss_tot > 1e-12 else 0.0
    return ([a, b], r2, residuals)


def _fit_power(xs: List[float], ys: List[float]) -> Tuple[List[float], float, List[float]]:
    """Fit y = a * x^b. Returns ([a, b], r2, residuals).

    Falls back to ([0, 0], 0, ...) if any x ≤ 0 or y ≤ 0 (log undefined).
    """
    if any(x <= 0 for x in xs) or any(y <= 0 for y in ys):
        return ([0.0, 0.0], 0.0, [0.0] * len(xs))
    # Linearize: log(y) = log(a) + b*log(x)
    log_xs = [math.log(x) for x in xs]
    log_ys = [math.log(y) for y in ys]
    ([log_a, b], r2_log, _) = _fit_linear(log_xs, log_ys)
    a = math.exp(log_a)
    y_pred = [a * (x ** b) for x in xs]
    residuals = [yp - ya for yp, ya in zip(y_pred, ys)]
    # Compute R² in original space (not log space) — honest fit quality
    n = len(ys)
    mean_y = sum(ys) / n
    ss_tot = sum((y - mean_y) ** 2 for y in ys)
    ss_res = sum(r ** 2 for r in residuals)
    r2 = 1.0 - (ss_res / ss_tot) if ss_tot > 1e-12 else 0.0
    return ([a, b], r2, residuals)


def _fit_exponential(xs: List[float], ys: List[float]) -> Tuple[List[float], float, List[float]]:
    """Fit y = a * exp(b * x). Returns ([a, b], r2, residuals)."""
    if any(y <= 0 for y in ys):
        return ([0.0, 0.0], 0.0, [0.0] * len(xs))
    log_ys = [math.log(y) for y in ys]
    ([log_a, b], r2_log, _) = _fit_linear(xs, log_ys)
    a = math.exp(log_a)
    y_pred = [a * math.exp(b * x) for x in xs]
    residuals = [yp - ya for yp, ya in zip(y_pred, ys)]
    n = len(ys)
    mean_y = sum(ys) / n
    ss_tot = sum((y - mean_y) ** 2 for y in ys)
    ss_res = sum(r ** 2 for r in residuals)
    r2 = 1.0 - (ss_res / ss_tot) if ss_tot > 1e-12 else 0.0
    return ([a, b], r2, residuals)


def _fit_logarithmic(xs: List[float], ys: List[float]) -> Tuple[List[float], float, List[float]]:
    """Fit y = a * log(x) + b. Returns ([a, b], r2, residuals)."""
    if any(x <= 0 for x in xs):
        return ([0.0, 0.0], 0.0, [0.0] * len(xs))
    log_xs = [math.log(x) for x in xs]
    return _fit_linear(log_xs, ys)


def _fit_inverse(xs: List[float], ys: List[float]) -> Tuple[List[float], float, List[float]]:
    """Fit y = a / x + b. Returns ([a, b], r2, residuals)."""
    if any(abs(x) < 1e-12 for x in xs):
        return ([0.0, 0.0], 0.0, [0.0] * len(xs))
    inv_xs = [1.0 / x for x in xs]
    return _fit_linear(inv_xs, ys)


def _fit_quadratic(xs: List[float], ys: List[float]) -> Tuple[List[float], float, List[float]]:
    """Fit y = a*x^2 + b*x + c. Returns ([a, b, c], r2, residuals).

    Uses the normal equations for least-squares polynomial fitting.
    """
    n = len(xs)
    if n < 3:
        return ([0.0, 0.0, 0.0], 0.0, [0.0] * n)
    # Build the design matrix columns: [x^2, x, 1]
    s_x4 = sum(x ** 4 for x in xs)
    s_x3 = sum(x ** 3 for x in xs)
    s_x2 = sum(x ** 2 for x in xs)
    s_x = sum(xs)
    s_x2y = sum((x ** 2) * y for x, y in zip(xs, ys))
    s_xy = sum(x * y for x, y in zip(xs, ys))
    s_y = sum(ys)
    # Normal equations: [[s_x4, s_x3, s_x2], [s_x3, s_x2, s_x], [s_x2, s_x, n]]
    #                  *  [a, b, c]^T = [s_x2y, s_xy, s_y]^T
    # Solve via Cramer's rule for 3x3
    A = [[s_x4, s_x3, s_x2],
         [s_x3, s_x2, s_x],
         [s_x2, s_x, float(n)]]
    B = [s_x2y, s_xy, s_y]

    def det3(m):
        return (m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1])
                - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
                + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0]))

    D = det3(A)
    if abs(D) < 1e-12:
        return ([0.0, 0.0, 0.0], 0.0, [0.0] * n)

    def replace_col(m, c, v):
        return [[v[i] if j == c else m[i][j] for j in range(3)] for i in range(3)]

    Da = det3(replace_col(A, 0, B))
    Db = det3(replace_col(A, 1, B))
    Dc = det3(replace_col(A, 2, B))
    a, b, c = Da / D, Db / D, Dc / D

    y_pred = [a * x * x + b * x + c for x in xs]
    residuals = [yp - ya for yp, ya in zip(y_pred, ys)]
    mean_y = s_y / n
    ss_tot = sum((y - mean_y) ** 2 for y in ys)
    ss_res = sum(r ** 2 for r in residuals)
    r2 = 1.0 - (ss_res / ss_tot) if ss_tot > 1e-12 else 0.0
    return ([a, b, c], r2, residuals)


# Library of candidate law forms (ordered by Occam's razor: simpler first)
CANDIDATE_LAWS: List[LawCandidate] = [
    LawCandidate(name="linear",       form="y = a*x + b",
                fit_func=_fit_linear,       param_names=["a", "b"]),
    LawCandidate(name="inverse",      form="y = a/x + b",
                fit_func=_fit_inverse,      param_names=["a", "b"]),
    LawCandidate(name="logarithmic",  form="y = a*log(x) + b",
                fit_func=_fit_logarithmic,  param_names=["a", "b"]),
    LawCandidate(name="power",        form="y = a * x^b",
                fit_func=_fit_power,        param_names=["a", "b"]),
    LawCandidate(name="exponential",  form="y = a * exp(b*x)",
                fit_func=_fit_exponential,  param_names=["a", "b"]),
    LawCandidate(name="quadratic",    form="y = a*x^2 + b*x + c",
                fit_func=_fit_quadratic,    param_names=["a", "b", "c"]),
]


# ---------------------------------------------------------------------------
# Law (the discovered law) — uses discovery_graph.Law dataclass semantics
# ---------------------------------------------------------------------------

@dataclass
class DiscoveredLaw:
    """The law discovered by BACON for a given (x, y) dataset.

    Fields mirror invention_compiler.discovery_graph.Law where applicable
    so the discovered law can be promoted into the DiscoveryGraph.
    """
    name: str                  # candidate name, e.g., "power"
    form: str                  # human-readable form, e.g., "y = a * x^b"
    params: List[float]        # fitted coefficients
    param_names: List[str]
    r2: float                  # coefficient of determination in [0, 1]
    residuals: List[float]    # per-point residuals
    n_points: int              # number of data points
    falsifiable_by: str        # how to falsify this law

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "form": self.form,
            "params": self.params,
            "param_names": self.param_names,
            "r2": self.r2,
            "n_points": self.n_points,
            "falsifiable_by": self.falsifiable_by,
            "max_residual": max(abs(r) for r in self.residuals) if self.residuals else 0.0,
        }

    def __str__(self) -> str:
        param_strs = [f"{n}={p:.6g}" for n, p in zip(self.param_names, self.params)]
        return (f"DiscoveredLaw(name={self.name}, form='{self.form}', "
                f"params=[{', '.join(param_strs)}], R²={self.r2:.4f}, "
                f"n_points={self.n_points})")


# ---------------------------------------------------------------------------
# BACON engine
# ---------------------------------------------------------------------------

# Falsifiability threshold: a law with R² below this is rejected.
# Per "no data, say no data" principle: a weak fit is reported as no-fit.
R2_FALSIFIABILITY_THRESHOLD = 0.5


def discover_law(xs: List[float], ys: List[float],
                 x_label: str = "x", y_label: str = "y",
                 threshold: float = R2_FALSIFIABILITY_THRESHOLD,
                 verbose: bool = False
                 ) -> Optional[DiscoveredLaw]:
    """Discover the best-fitting law from (x, y) data.

    Tries every candidate law form in CANDIDATE_LAWS, fits each by
    least-squares, and returns the one with the highest R² that exceeds
    the threshold. If no candidate meets the threshold, returns None
    (no law preferred over a weak fit — per "no data, say no data").

    Args:
        xs: input data (independent variable)
        ys: output data (dependent variable)
        x_label: name of the x variable (for falsification description)
        y_label: name of the y variable (for falsification description)
        threshold: minimum R² required for a law to be accepted
        verbose: if True, print fit results for every candidate

    Returns:
        DiscoveredLaw if a candidate exceeds the threshold, else None.
    """
    if len(xs) != len(ys):
        raise ValueError(f"length mismatch: {len(xs)} xs vs {len(ys)} ys")
    if len(xs) < 3:
        # Cannot meaningfully fit a 2-parameter law with fewer than 3 points
        return None

    best: Optional[DiscoveredLaw] = None
    best_r2: float = threshold  # must EXCEED the threshold to be accepted

    for candidate in CANDIDATE_LAWS:
        try:
            params, r2, residuals = candidate.fit_func(xs, ys)
        except (ValueError, OverflowError, ZeroDivisionError):
            # Some candidates are undefined for certain data (e.g., log of negative)
            if verbose:
                print(f"  {candidate.name:12s} — undefined for this data, skipped")
            continue

        if verbose:
            param_strs = [f"{n}={p:.4g}" for n, p in zip(candidate.param_names, params)]
            print(f"  {candidate.name:12s} R²={r2:.4f}  params=[{', '.join(param_strs)}]")

        if r2 > best_r2:
            best_r2 = r2
            best = DiscoveredLaw(
                name=candidate.name,
                form=candidate.form,
                params=params,
                param_names=list(candidate.param_names),
                r2=r2,
                residuals=residuals,
                n_points=len(xs),
                falsifiable_by=(
                    f"Measure ({x_label}, {y_label}) at a value not in the training set. "
                    f"If the predicted {y_label} differs from observed by more than "
                    f"{max(abs(r) for r in residuals):.4g}, the law is falsified."
                ),
            )

    return best


def discover_laws_from_dataset(dataset: Dict[str, List[float]],
                                target_var: str,
                                independent_vars: Optional[List[str]] = None,
                                threshold: float = R2_FALSIFIABILITY_THRESHOLD,
                                verbose: bool = False
                                ) -> Dict[str, Optional[DiscoveredLaw]]:
    """Discover laws between each independent variable and the target.

    For multivariate data, BACON tries to discover the best law between
    each (independent_var, target) pair. This is the simple version of
    Langley's BACON.1: it does not compose variables (BACON.3) or
    discover hidden variables (BACON.4) — those are Phase IV.

    Args:
        dataset: dict mapping variable name → list of values
        target_var: the dependent variable to discover laws for
        independent_vars: list of vars to try as predictors (default: all
            vars except target_var)
        threshold: minimum R² required
        verbose: if True, print fit details

    Returns:
        dict mapping independent_var → DiscoveredLaw (or None if no law fits)
    """
    if target_var not in dataset:
        raise ValueError(f"target_var '{target_var}' not in dataset")
    if independent_vars is None:
        independent_vars = [v for v in dataset if v != target_var]

    results: Dict[str, Optional[DiscoveredLaw]] = {}
    for var in independent_vars:
        if var not in dataset:
            continue
        if len(dataset[var]) != len(dataset[target_var]):
            continue
        law = discover_law(dataset[var], dataset[target_var],
                           x_label=var, y_label=target_var,
                           threshold=threshold, verbose=verbose)
        results[var] = law
    return results


# ---------------------------------------------------------------------------
# BACON.3 — variable composition (Phase IV, cycle 51)
# ---------------------------------------------------------------------------

@dataclass
class ComposedLaw:
    """A multivariate law discovered by BACON.3 — composition of variables.

    BACON.3 (Langley, 1981) extends BACON.1 by composing variables:
    if y is not a clean function of any single x_i, BACON.3 tries
    products, ratios, and sums of variables. Example: if y = a * x1 * x2,
    BACON.3 computes z = x1 * x2, then fits y = a * z + b (linear in z).

    This module supports 4 composition operators:
      - product:   z = x1 * x2
      - ratio:     z = x1 / x2 (and x2 / x1)
      - sum:       z = x1 + x2
      - difference: z = x1 - x2

    For each composition, BACON.3 then runs single-variable discover_law()
    on (z, y). If R²(z, y) > R²(any single x_i, y), the composition
    captures the multivariate law that single-variable fits missed.
    """
    composition_op: str         # "product", "ratio", "sum", "difference"
    input_vars: List[str]       # which variables were composed
    composed_var_label: str     # human-readable, e.g., "T_dry_C * RH_pct"
    composed_values: List[float]  # the z = compose(x1, x2) values
    law: DiscoveredLaw           # the single-variable law fit on (z, y)
    r2_improvement: float       # how much R² improved over best single-variable fit

    def to_dict(self) -> Dict[str, Any]:
        return {
            "composition_op": self.composition_op,
            "input_vars": self.input_vars,
            "composed_var_label": self.composed_var_label,
            "law": self.law.to_dict(),
            "r2_improvement": self.r2_improvement,
        }

    def __str__(self) -> str:
        return (f"ComposedLaw(op='{self.composition_op}', "
                f"vars={self.input_vars}, z='{self.composed_var_label}', "
                f"law={self.law.name}, R²={self.law.r2:.4f}, "
                f"improvement=+{self.r2_improvement:.4f})")


def _compose_product(xs1: List[float], xs2: List[float]) -> List[float]:
    return [a * b for a, b in zip(xs1, xs2)]


def _compose_ratio(xs1: List[float], xs2: List[float]) -> Optional[List[float]]:
    if any(abs(b) < 1e-12 for b in xs2):
        return None
    return [a / b for a, b in zip(xs1, xs2)]


def _compose_sum(xs1: List[float], xs2: List[float]) -> List[float]:
    return [a + b for a, b in zip(xs1, xs2)]


def _compose_difference(xs1: List[float], xs2: List[float]) -> List[float]:
    return [a - b for a, b in zip(xs1, xs2)]


COMPOSITION_OPS: Dict[str, Any] = {
    "product": _compose_product,
    "ratio": _compose_ratio,
    "sum": _compose_sum,
    "difference": _compose_difference,
}


def discover_composed_law(dataset: Dict[str, List[float]],
                          target_var: str,
                          independent_vars: Optional[List[str]] = None,
                          threshold: float = R2_FALSIFIABILITY_THRESHOLD,
                          verbose: bool = False
                          ) -> Optional[ComposedLaw]:
    """Discover a multivariate law by composing pairs of variables.

    BACON.3 algorithm (simplified):
      1. For each pair (x_i, x_j) of independent variables, compute
         z = x_i OP x_j for each composition operator.
      2. Run single-variable discover_law(z, y) for each composed z.
      3. Return the composition whose law has the highest R² that EXCEEDS
         the best single-variable R² by at least 0.01 (improvement must
         be material — a 0.001 improvement is noise).

    Args:
        dataset: dict mapping variable name → list of values
        target_var: the dependent variable
        independent_vars: which vars to compose (default: all non-target)
        threshold: minimum R² required for the composed law
        verbose: if True, print fit details for each composition tried

    Returns:
        ComposedLaw if a composition materially improves R², else None.
    """
    if target_var not in dataset:
        raise ValueError(f"target_var '{target_var}' not in dataset")
    if independent_vars is None:
        independent_vars = [v for v in dataset if v != target_var]
    if len(independent_vars) < 2:
        return None  # BACON.3 requires ≥2 variables to compose

    ys = dataset[target_var]

    # Baseline: best single-variable fit
    single_results = discover_laws_from_dataset(
        dataset, target_var, independent_vars, threshold=0.0  # get R² even if below threshold
    )
    best_single_r2 = max(
        (law.r2 for law in single_results.values() if law is not None),
        default=0.0,
    )
    if verbose:
        print(f"  BACON.3 baseline: best single-variable R² = {best_single_r2:.4f}")

    best: Optional[ComposedLaw] = None
    best_r2 = best_single_r2 + 0.01  # must improve by ≥0.01

    # Try every (i, j) pair with i < j (avoid duplicates) and every operator
    for idx_i in range(len(independent_vars)):
        for idx_j in range(idx_i + 1, len(independent_vars)):
            vi = independent_vars[idx_i]
            vj = independent_vars[idx_j]
            xs_i = dataset[vi]
            xs_j = dataset[vj]
            if len(xs_i) != len(ys) or len(xs_j) != len(ys):
                continue

            for op_name, op_func in COMPOSITION_OPS.items():
                # ratio is directional — try both directions
                if op_name == "ratio":
                    composed = op_func(xs_i, xs_j)
                    composed_label = f"{vi} / {vj}"
                else:
                    composed = op_func(xs_i, xs_j)
                    composed_label = f"{vi} {op_name} {vj}".replace("product", "*").replace("sum", "+").replace("difference", "-")

                if composed is None:
                    if verbose:
                        print(f"  skip {vi} {op_name} {vj} — undefined (division by zero)")
                    continue

                law = discover_law(composed, ys, x_label=composed_label,
                                   y_label=target_var, threshold=0.0)  # get R² regardless
                if law is None:
                    continue

                if verbose:
                    print(f"  try z = {composed_label:30s} → {law.name:10s} R²={law.r2:.4f}")

                if law.r2 > best_r2:
                    best_r2 = law.r2
                    best = ComposedLaw(
                        composition_op=op_name,
                        input_vars=[vi, vj],
                        composed_var_label=composed_label,
                        composed_values=composed,
                        law=law,
                        r2_improvement=law.r2 - best_single_r2,
                    )

    # Apply threshold to the final result
    if best is not None and best.law.r2 >= threshold:
        return best
    return None


# ---------------------------------------------------------------------------
# Cross-validation (Phase IV, cycle 51)
# ---------------------------------------------------------------------------

@dataclass
class CrossValidatedLaw:
    """The result of cross-validating a discovered law.

    Per ANTI_ENTROPY.md "Don't reward agreement with priors": fitting
    a law and reporting R² on the SAME data is in-sample fit, which
    overclaims. Real scientific discovery requires generalization —
    fit on training data, predict held-out test data, compute test R².

    This dataclass carries both:
      - training R² (in-sample, optimistic)
      - test R² (out-of-sample, honest)
      - test residuals (per-point prediction errors on held-out data)
      - generalization_gap = train_R² - test_R² (large gap = overfitting)
    """
    law: DiscoveredLaw          # the law fit on training data
    train_r2: float             # R² on training set (80% of data)
    test_r2: float              # R² on test set (20% held out)
    test_residuals: List[float]  # (y_pred - y_actual) on test set
    generalization_gap: float   # train_r2 - test_r2 (≥0; large = overfitting)
    n_train: int
    n_test: int

    @property
    def generalizes(self) -> bool:
        """A law generalizes if test R² is within 0.10 of train R²."""
        return self.generalization_gap <= 0.10 and self.test_r2 >= R2_FALSIFIABILITY_THRESHOLD

    def to_dict(self) -> Dict[str, Any]:
        return {
            "law": self.law.to_dict(),
            "train_r2": self.train_r2,
            "test_r2": self.test_r2,
            "generalization_gap": self.generalization_gap,
            "n_train": self.n_train,
            "n_test": self.n_test,
            "generalizes": self.generalizes,
        }

    def __str__(self) -> str:
        return (f"CrossValidatedLaw(law={self.law.name}, "
                f"train R²={self.train_r2:.4f}, test R²={self.test_r2:.4f}, "
                f"gap={self.generalization_gap:.4f}, "
                f"{'GENERALIZES' if self.generalizes else 'OVERFIT'})")


def cross_validate_law(xs: List[float], ys: List[float],
                       test_fraction: float = 0.2,
                       threshold: float = R2_FALSIFIABILITY_THRESHOLD
                       ) -> Optional[CrossValidatedLaw]:
    """Cross-validate a discovered law on held-out test data.

    Splits (x, y) into 80% train + 20% test. Fits BACON on train,
    predicts test, computes test R². Returns the cross-validated law
    with generalization gap, or None if no law passes the threshold.

    Per ANTI_ENTROPY.md "Don't reward agreement with priors": this is
    the honest fit — if a law has high train R² but low test R², it
    overfit. A real scientific law must generalize.

    Deterministic split: take every (1/test_fraction)-th point as test,
    rest as train. This is reproducible per "use the word 'engine'
    honestly" rule (no RNG).

    Args:
        xs: input data
        ys: output data
        test_fraction: fraction of data to hold out (default 0.2 = 20%)
        threshold: minimum TEST R² required for the law to "generalize"

    Returns:
        CrossValidatedLaw if a law is discovered and tested, else None.
    """
    n = len(xs)
    if n < 5:  # need ≥5 points for meaningful 80/20 split
        return None
    if len(xs) != len(ys):
        raise ValueError("length mismatch")

    # Deterministic test set: every k-th point is test
    k = max(1, round(1.0 / test_fraction))
    test_indices = set(i for i in range(n) if i % k == 0)
    train_xs = [xs[i] for i in range(n) if i not in test_indices]
    train_ys = [ys[i] for i in range(n) if i not in test_indices]
    test_xs = [xs[i] for i in test_indices]
    test_ys = [ys[i] for i in test_indices]

    # Fit on training
    train_law = discover_law(train_xs, train_ys, threshold=0.0)  # always fit
    if train_law is None:
        return None

    # Predict on test set using the train-law's params
    # We need to compute y_pred for each test x using the fitted law's form/params
    test_y_pred = _predict_with_law(train_law, test_xs)
    if test_y_pred is None:
        return None  # law form not predictable (shouldn't happen)

    # Compute test R²
    n_test = len(test_ys)
    mean_test_y = sum(test_ys) / n_test
    ss_tot = sum((y - mean_test_y) ** 2 for y in test_ys)
    test_residuals = [yp - ya for yp, ya in zip(test_y_pred, test_ys)]
    ss_res = sum(r ** 2 for r in test_residuals)
    test_r2 = 1.0 - (ss_res / ss_tot) if ss_tot > 1e-12 else 0.0

    # Compute train R² (re-fit on training only)
    # train_law.r2 IS the train R² already (computed in discover_law)
    train_r2 = train_law.r2

    return CrossValidatedLaw(
        law=train_law,
        train_r2=train_r2,
        test_r2=test_r2,
        test_residuals=test_residuals,
        generalization_gap=train_r2 - test_r2,
        n_train=len(train_xs),
        n_test=n_test,
    )


def _predict_with_law(law: DiscoveredLaw, xs: List[float]) -> Optional[List[float]]:
    """Predict y values for xs using the law's form and fitted params."""
    if law.name == "linear":
        a, b = law.params
        return [a * x + b for x in xs]
    if law.name == "inverse":
        a, b = law.params
        if any(abs(x) < 1e-12 for x in xs):
            return None
        return [a / x + b for x in xs]
    if law.name == "logarithmic":
        a, b = law.params
        if any(x <= 0 for x in xs):
            return None
        return [a * math.log(x) + b for x in xs]
    if law.name == "power":
        a, b = law.params
        if any(x <= 0 for x in xs):
            return None
        return [a * (x ** b) for x in xs]
    if law.name == "exponential":
        a, b = law.params
        return [a * math.exp(b * x) for x in xs]
    if law.name == "quadratic":
        a, b, c = law.params
        return [a * x * x + b * x + c for x in xs]
    return None


# ---------------------------------------------------------------------------
# BACON.4 — recursive composition (Phase V, cycle 52)
# ---------------------------------------------------------------------------

@dataclass
class RecursiveComposedLaw:
    """A multivariate law discovered by BACON.4 — recursive composition.

    BACON.4 extends BACON.3 by composing 3+ variables recursively. If
    y = a * x1 * x2 * x3, BACON.3 can find y = a * (x1 * x2) but only if
    x3 happens to be constant or correlates with x1*x2. BACON.4 takes
    the composed variable z = x1 * x2 from BACON.3 and tries z * x3, z / x3,
    etc., discovering the 3-variable product.

    This dataclass carries the full composition chain so the discovered
    law can be unwound into a human-readable multivariate expression.
    """
    # The final single-variable law (fit on the fully-composed variable)
    law: DiscoveredLaw
    # The full composition chain, e.g., ["x1 * x2", "(x1 * x2) * x3"]
    composition_chain: List[str]
    # The variables involved (e.g., ["x1", "x2", "x3"])
    input_vars: List[str]
    # The final composed values (z = ((x1 * x2) * x3))
    composed_values: List[float]
    # R² improvement over best single-variable fit
    r2_improvement: float
    # Depth of recursion (2 = BACON.3 equivalent, 3 = first true BACON.4 level)
    depth: int

    def to_dict(self) -> Dict[str, Any]:
        return {
            "law": self.law.to_dict(),
            "composition_chain": self.composition_chain,
            "input_vars": self.input_vars,
            "r2_improvement": self.r2_improvement,
            "depth": self.depth,
        }

    def __str__(self) -> str:
        chain_str = " → ".join(self.composition_chain)
        return (f"RecursiveComposedLaw(depth={self.depth}, "
                f"vars={self.input_vars}, chain=[{chain_str}], "
                f"law={self.law.name}, R²={self.law.r2:.4f}, "
                f"improvement=+{self.r2_improvement:.4f})")


def discover_recursive_composed_law(dataset: Dict[str, List[float]],
                                      target_var: str,
                                      independent_vars: Optional[List[str]] = None,
                                      max_depth: int = 3,
                                      threshold: float = R2_FALSIFIABILITY_THRESHOLD,
                                      verbose: bool = False
                                      ) -> Optional[RecursiveComposedLaw]:
    """Discover a multivariate law by recursively composing variables.

    BACON.4 algorithm:
      1. Run BACON.3 (discover_composed_law) on the dataset to get z = x_i OP x_j.
      2. Replace x_i and x_j in the dataset with the composed variable z.
      3. Recursively run BACON.3 on the reduced dataset (z, remaining vars).
      4. Stop when no composition materially improves R², OR max_depth reached.

    This discovers laws like y = a * x1 * x2 * x3 (depth 3), which BACON.3
    cannot find unless x3 happens to be constant.

    Args:
        dataset: dict mapping variable name → list of values
        target_var: the dependent variable
        independent_vars: which vars to compose (default: all non-target)
        max_depth: maximum recursion depth (default 3 — products of 3 vars)
        threshold: minimum R² required for the final composed law
        verbose: if True, print fit details for each composition tried

    Returns:
        RecursiveComposedLaw if recursion discovers a deeper law, else None.
    """
    if target_var not in dataset:
        raise ValueError(f"target_var '{target_var}' not in dataset")
    if independent_vars is None:
        independent_vars = [v for v in dataset if v != target_var]
    if len(independent_vars) < 2:
        return None

    ys = list(dataset[target_var])

    # Baseline: best single-variable fit
    single_results = discover_laws_from_dataset(
        dataset, target_var, independent_vars, threshold=0.0
    )
    best_single_r2 = max(
        (law.r2 for law in single_results.values() if law is not None),
        default=0.0,
    )
    if verbose:
        print(f"  BACON.4 baseline: best single-variable R² = {best_single_r2:.4f}")

    # Start with the original dataset
    current_dataset = dict(dataset)
    current_vars = list(independent_vars)
    composition_chain: List[str] = []
    composed_var_label = None
    composed_values = None
    depth = 0

    # Recursively compose
    for d in range(1, max_depth + 1):
        if len(current_vars) < 2:
            break
        # Try BACON.3 at this depth
        composed = discover_composed_law(
            current_dataset, target_var, current_vars, threshold=0.0, verbose=verbose
        )
        if composed is None:
            if verbose:
                print(f"  depth {d}: no composition improves R² — stop")
            break
        if composed.law.r2 <= best_single_r2 + 0.01:
            if verbose:
                print(f"  depth {d}: improvement < 0.01 — stop")
            break
        if verbose:
            print(f"  depth {d}: z = {composed.composed_var_label} → R²={composed.law.r2:.4f}")

        # Record this composition step
        composition_chain.append(composed.composed_var_label)
        composed_var_label = composed.composed_var_label
        composed_values = composed.composed_values
        depth = d

        # Reduce dataset: remove the two input vars, add the composed var
        new_dataset = {target_var: ys, composed_var_label: composed_values}
        for v in current_vars:
            if v not in composed.input_vars:
                new_dataset[v] = current_dataset[v]
        current_dataset = new_dataset
        current_vars = [composed_var_label] + [
            v for v in current_vars if v not in composed.input_vars
        ]
        # Continue to next depth

    if depth < 2:
        # depth=1 is just BACON.3; BACON.4 requires depth ≥2
        if verbose:
            print(f"  BACON.4 final depth {depth} < 2 — not BACON.4, return None")
        return None

    # Re-fit on the final composed values
    final_law = discover_law(composed_values, ys, threshold=0.0)
    if final_law is None:
        return None
    if final_law.r2 < threshold:
        if verbose:
            print(f"  BACON.4 final R²={final_law.r2:.4f} < threshold {threshold}")
        return None

    # Collect all original input vars from the chain
    # Parse the chain to recover variable names (handles "(x1 * x2) * x3" etc.)
    all_vars: List[str] = []
    for step in composition_chain:
        for token in step.replace("(", " ").replace(")", " ").split():
            # Strip operator characters
            cleaned = token.strip("*/+-")
            if cleaned and cleaned not in all_vars and not cleaned.startswith("'"):
                all_vars.append(cleaned)

    return RecursiveComposedLaw(
        law=final_law,
        composition_chain=composition_chain,
        input_vars=all_vars,
        composed_values=composed_values,
        r2_improvement=final_law.r2 - best_single_r2,
        depth=depth,
    )


# ---------------------------------------------------------------------------
# k-fold cross-validation (Phase V, cycle 52)
# ---------------------------------------------------------------------------

@dataclass
class KFoldCrossValidatedLaw:
    """The result of k-fold cross-validation.

    Per ANTI_ENTROPY.md "Don't reward agreement with priors": single 80/20
    split can miss fold-to-fold variance. If the law's R² varies wildly
    across folds, it's unstable — even if the average is high.

    This dataclass carries:
      - per-fold train/test R²
      - mean test R² (the honest quality metric)
      - test R² std deviation (stability metric)
      - the law fit on the FULL dataset (final, deployed law)
    """
    law: DiscoveredLaw            # the law fit on ALL data (final deployment)
    fold_train_r2: List[float]    # per-fold train R² (length k)
    fold_test_r2: List[float]    # per-fold test R² (length k)
    mean_test_r2: float          # mean of fold_test_r2 (the honest metric)
    std_test_r2: float           # std dev of fold_test_r2 (stability)
    k: int                        # number of folds
    generalizes: bool             # True if mean_test_r2 ≥ threshold AND std ≤ 0.10

    def to_dict(self) -> Dict[str, Any]:
        return {
            "law": self.law.to_dict(),
            "fold_train_r2": self.fold_train_r2,
            "fold_test_r2": self.fold_test_r2,
            "mean_test_r2": self.mean_test_r2,
            "std_test_r2": self.std_test_r2,
            "k": self.k,
            "generalizes": self.generalizes,
        }

    def __str__(self) -> str:
        return (f"KFoldCrossValidatedLaw(law={self.law.name}, k={self.k}, "
                f"mean_test_R²={self.mean_test_r2:.4f}, "
                f"std={self.std_test_r2:.4f}, "
                f"{'GENERALIZES' if self.generalizes else 'UNSTABLE'})")


def k_fold_cross_validate_law(xs: List[float], ys: List[float],
                              k: int = 5,
                              threshold: float = R2_FALSIFIABILITY_THRESHOLD
                              ) -> Optional[KFoldCrossValidatedLaw]:
    """k-fold cross-validation of a discovered law.

    Splits (x, y) into k contiguous folds. For each fold i:
      - train = all other folds (k-1 folds)
      - test = fold i
      - fit BACON on train, predict test, compute test R²

    Returns the law (fit on ALL data) with per-fold R², mean test R²,
    and std test R². A law "generalizes" if mean_test_r2 ≥ threshold
    AND std_test_r2 ≤ 0.10 (stable across folds).

    Deterministic: contiguous folds, no shuffling, no RNG. Reproducible
    per "use the word 'engine' honestly" rule.

    Args:
        xs: input data
        ys: output data
        k: number of folds (default 5)
        threshold: minimum mean test R² required to "generalize"

    Returns:
        KFoldCrossValidatedLaw if a law is discovered, else None.
    """
    n = len(xs)
    if n < k * 2:  # need ≥2 points per fold for meaningful train/test
        return None
    if len(xs) != len(ys):
        raise ValueError("length mismatch")
    if k < 2:
        raise ValueError(f"k must be ≥2, got {k}")

    # Compute fold boundaries (contiguous)
    fold_size = n // k
    remainder = n % k
    folds: List[List[int]] = []
    start = 0
    for i in range(k):
        size = fold_size + (1 if i < remainder else 0)
        folds.append(list(range(start, start + size)))
        start += size

    fold_train_r2: List[float] = []
    fold_test_r2: List[float] = []

    for i in range(k):
        test_idx = set(folds[i])
        train_xs = [xs[j] for j in range(n) if j not in test_idx]
        train_ys = [ys[j] for j in range(n) if j not in test_idx]
        test_xs = [xs[j] for j in test_idx]
        test_ys = [ys[j] for j in test_idx]

        # Fit on train
        train_law = discover_law(train_xs, train_ys, threshold=0.0)
        if train_law is None:
            return None  # no law fits the train set

        fold_train_r2.append(train_law.r2)

        # Predict test
        test_y_pred = _predict_with_law(train_law, test_xs)
        if test_y_pred is None:
            return None
        n_test = len(test_ys)
        if n_test == 0:
            continue
        mean_test_y = sum(test_ys) / n_test
        ss_tot = sum((y - mean_test_y) ** 2 for y in test_ys)
        test_residuals = [yp - ya for yp, ya in zip(test_y_pred, test_ys)]
        ss_res = sum(r ** 2 for r in test_residuals)
        test_r2 = 1.0 - (ss_res / ss_tot) if ss_tot > 1e-12 else 0.0
        fold_test_r2.append(test_r2)

    # Final law fit on ALL data
    final_law = discover_law(xs, ys, threshold=0.0)
    if final_law is None:
        return None

    mean_test = sum(fold_test_r2) / len(fold_test_r2)
    if len(fold_test_r2) > 1:
        variance = sum((r - mean_test) ** 2 for r in fold_test_r2) / len(fold_test_r2)
        std_test = math.sqrt(variance)
    else:
        std_test = 0.0

    generalizes = (mean_test >= threshold) and (std_test <= 0.10)

    return KFoldCrossValidatedLaw(
        law=final_law,
        fold_train_r2=fold_train_r2,
        fold_test_r2=fold_test_r2,
        mean_test_r2=mean_test,
        std_test_r2=std_test,
        k=k,
        generalizes=generalizes,
    )


# ---------------------------------------------------------------------------
# Real data generators — wrap the existing formula modules as datasets
# ---------------------------------------------------------------------------

def stull_wet_bulb_dataset(n_points: int = 20) -> Dict[str, List[float]]:
    """Generate a real Stull wet-bulb dataset.

    Samples (T, RH) pairs uniformly in the formula's valid range, then
    computes T_wb via the Stull 2011 formula. This is REAL data — it
    comes from a published scientific formula, not a synthetic noise model.

    The expected law BACON should discover: T_wb is roughly linear in T
    (with weak RH dependence that's not captured by single-variable BACON).
    """
    from scripts.formulas.stull_wet_bulb import stull_wet_bulb
    # Deterministic grid (no RNG — reproducible per "use the word engine honestly")
    Ts = []
    RHs = []
    Twbs = []
    n_t = int(math.sqrt(n_points))
    n_rh = max(1, n_points // n_t)
    for i in range(n_t):
        T = -20 + (50 - (-20)) * i / max(1, n_t - 1)  # -20 to 50 °C
        for j in range(n_rh):
            RH = 5 + (99 - 5) * j / max(1, n_rh - 1)  # 5 to 99 %
            Twb = stull_wet_bulb(T, RH)
            Ts.append(T)
            RHs.append(RH)
            Twbs.append(Twb)
    return {"T_dry_C": Ts, "RH_pct": RHs, "T_wet_C": Twbs}


def stefan_boltzmann_dataset(n_points: int = 15) -> Dict[str, List[float]]:
    """Generate a real Stefan-Boltzmann radiative cooling dataset.

    Varies surface temperature T_surface while holding ε=0.95, A=1 m²,
    T_sky=270 K. The expected law BACON should discover: Q ∝ T_surface^4
    (the Stefan-Boltzmann T^4 law), which is the power form y = a*x^b
    with b ≈ 4.

    This is the Kepler test for BACON: can it discover a power law from
    real (T, Q) data? If yes, the engine is verified.
    """
    from scripts.formulas.stefan_boltzmann import stefan_boltzmann_radiative_cooling
    Ts = []
    Qs = []
    for i in range(n_points):
        T_surface_K = 280 + 100 * i / max(1, n_points - 1)  # 280 to 380 K
        Q = stefan_boltzmann_radiative_cooling(
            epsilon=0.95, A=1.0, T_surface=T_surface_K, T_sky=270.0
        )
        Ts.append(T_surface_K)
        Qs.append(Q)
    return {"T_surface_K": Ts, "Q_W": Qs}


def pcm_latent_heat_dataset(n_points: int = 10) -> Dict[str, List[float]]:
    """Generate a real PCM latent-heat dataset using the existing sizing formula.

    pcm_latent_heat_sizing(Q_daily, t_hours, L_pcm) = m_pcm

    Holding L_pcm constant and varying Q_daily and t_hours, we get a
    linear law m = (3600 / L) * Q * t — a 2-input linear function.

    For single-variable BACON, we hold t constant and vary Q. The
    expected law: m_pcm ∝ Q_daily (linear, R² = 1.0 since the formula
    is exactly linear).
    """
    from scripts.formulas.pcm_latent_heat import pcm_latent_heat_sizing
    Qs = []
    ms = []
    L_pcm = 200_000  # 200 kJ/kg = 200,000 J/kg (paraffin wax)
    for i in range(n_points):
        Q_daily = 50 + 200 * i / max(1, n_points - 1)  # 50 to 250 W
        m = pcm_latent_heat_sizing(Q_daily=Q_daily, t_hours=8.0, L_pcm=L_pcm)
        Qs.append(Q_daily)
        ms.append(m)
    return {"Q_daily_W": Qs, "m_pcm_kg": ms}


# ---------------------------------------------------------------------------
# Autonomous hidden variable discovery (Phase VI, cycle 53)
# ---------------------------------------------------------------------------

@dataclass
class HiddenVariableDiscovery:
    """The result of autonomous hidden variable discovery.

    The system:
      1. Fits the best single-variable law for each candidate variable.
      2. Picks the best one (highest R²).
      3. Computes residuals.
      4. Searches over ALL OTHER variables — which one explains the residual?
      5. Reports the hidden variable + the combined law.

    NO HUMAN tells the system which variable to check. The system
    discovers the hidden variable autonomously.
    """
    primary_var: str
    primary_law: DiscoveredLaw
    hidden_var: str
    hidden_law: DiscoveredLaw
    single_r2: float
    combined_r2: float
    improvement: float

    @property
    def is_discovery(self) -> bool:
        """A discovery is genuine if the hidden variable explains ≥50% of the residual.

        The improvement (combined_r2 - single_r2) can be small even when the
        hidden variable perfectly explains the residual — this happens when
        the primary variable already captures most of the variance. The right
        metric is: does the hidden variable explain the RESIDUAL, not the total?
        """
        return self.hidden_law.r2 >= 0.50

    def to_dict(self) -> Dict[str, Any]:
        return {
            "primary_var": self.primary_var,
            "primary_law": self.primary_law.to_dict(),
            "hidden_var": self.hidden_var,
            "hidden_law": self.hidden_law.to_dict(),
            "single_r2": self.single_r2,
            "combined_r2": self.combined_r2,
            "improvement": self.improvement,
            "is_discovery": self.is_discovery,
        }

    def __str__(self) -> str:
        return (f"HiddenVariableDiscovery("
                f"primary={self.primary_var} ({self.primary_law.name}, R²={self.single_r2:.4f}), "
                f"hidden={self.hidden_var} ({self.hidden_law.name}, R²={self.hidden_law.r2:.4f}), "
                f"combined R²={self.combined_r2:.4f}, improvement=+{self.improvement:.4f}, "
                f"{'DISCOVERY' if self.is_discovery else 'marginal'})")


def discover_hidden_variable(dataset: Dict[str, List[float]],
                              target_var: str,
                              candidate_vars: Optional[List[str]] = None,
                              verbose: bool = False
                              ) -> Optional[HiddenVariableDiscovery]:
    """Autonomously discover which variable explains the residual.

    Per cycle 53 (Phase VI): the system searches over ALL candidate
    variables to find which one explains the residual after the best
    single-variable fit. NO HUMAN tells the system which variable to check.

    Algorithm:
      1. Fit best single-variable law for each candidate.
      2. Pick the best one (highest R²).
      3. Compute residuals.
      4. Search over ALL OTHER variables.
      5. Report the hidden variable + the combined law.

    Args:
        dataset: dict mapping variable name → list of values
        target_var: the dependent variable
        candidate_vars: which vars to search (default: all non-target)
        verbose: if True, print fit details

    Returns:
        HiddenVariableDiscovery if a hidden variable is found, else None.
    """
    if target_var not in dataset:
        raise ValueError(f"target_var '{target_var}' not in dataset")
    if candidate_vars is None:
        candidate_vars = [v for v in dataset if v != target_var]
    if len(candidate_vars) < 2:
        return None  # need ≥2 candidates to find a hidden variable

    ys = dataset[target_var]

    # Step 1-2: find best single-variable fit
    best_var = None
    best_law = None
    best_r2 = -1.0
    for var in candidate_vars:
        xs = dataset[var]
        if len(xs) != len(ys):
            continue
        law = discover_law(xs, ys, x_label=var, y_label=target_var, threshold=0.0)
        if law and law.r2 > best_r2:
            best_r2 = law.r2
            best_var = var
            best_law = law
        if verbose and law:
            print(f"  {var:15s} → {law.name:12s} R²={law.r2:.4f}")

    if best_law is None:
        return None
    if verbose:
        print(f"  Best primary: {best_var} (R²={best_r2:.4f})")

    # Step 3: compute residuals
    predictions = _predict_with_law(best_law, dataset[best_var])
    if predictions is None:
        return None
    residuals = [a - p for a, p in zip(ys, predictions)]

    # Step 4: search over OTHER variables
    hidden_var = None
    hidden_law = None
    hidden_r2 = -1.0
    for var in candidate_vars:
        if var == best_var:
            continue
        xs = dataset[var]
        if len(xs) != len(ys):
            continue
        law = discover_law(xs, residuals, x_label=var, y_label='residual', threshold=0.0)
        if law:
            if verbose:
                print(f"  residual vs {var:15s} → {law.name:12s} R²={law.r2:.4f}")
            if law.r2 > hidden_r2:
                hidden_r2 = law.r2
                hidden_var = var
                hidden_law = law

    if hidden_var is None or hidden_r2 < 0.05:
        return None
    if verbose:
        print(f"  Hidden variable: {hidden_var} (R²={hidden_r2:.4f})")

    # Step 5: compute combined R²
    hidden_preds = _predict_with_law(hidden_law, dataset[hidden_var])
    if hidden_preds is None:
        return None
    combined = [p + h for p, h in zip(predictions, hidden_preds)]
    combined_resid = [a - c for a, c in zip(ys, combined)]
    mean_y = sum(ys) / len(ys)
    ss_tot = sum((y - mean_y) ** 2 for y in ys)
    ss_res = sum(r ** 2 for r in combined_resid)
    combined_r2 = 1.0 - (ss_res / ss_tot) if ss_tot > 1e-12 else 0.0

    return HiddenVariableDiscovery(
        primary_var=best_var,
        primary_law=best_law,
        hidden_var=hidden_var,
        hidden_law=hidden_law,
        single_r2=best_r2,
        combined_r2=combined_r2,
        improvement=combined_r2 - best_r2,
    )
