"""
custodian.src.sampler — Deterministic sampling with external seed.

The seed must NOT be:
- generated by TEE
- generated from the benchmark contents
- chosen after observing TEE performance
- chosen by an evaluator attempting to optimize results

The resulting benchmark must be exactly reproducible from:
- corpus hash
- seed
- construction parameters
- sampler version
"""
import hashlib
import json
from typing import Dict, List, Optional, Tuple

SAMPLER_VERSION = "1.0.0"


class InsufficientCorpusError(Exception):
    """Raised when corpus has fewer valid independent cases than target N."""
    pass


class InsufficientDomainsError(Exception):
    """Raised when corpus has fewer than required domains."""
    pass


class DuplicateCaseError(Exception):
    """Raised when duplicate cases are detected."""
    pass


class DependentCaseClusterError(Exception):
    """Raised when too many cases share an independence_group."""
    pass


class TEEDependencyError(Exception):
    """Raised when construction parameters depend on TEE output."""
    pass


# Fields that MUST NOT appear in construction parameters (no TEE dependency)
FORBIDDEN_CONSTRUCTION_FIELDS = {
    "tee_score", "tee_failures", "tee_outputs", "tee_rankings",
    "tee_model_identity", "tee_performance", "tee_results",
}


def validate_construction_params(params: dict) -> None:
    """Validate that construction parameters do NOT depend on TEE output."""
    def check_recursive(obj, path=""):
        if isinstance(obj, dict):
            for key, value in obj.items():
                if key.lower() in FORBIDDEN_CONSTRUCTION_FIELDS:
                    raise TEEDependencyError(
                        f"CONSTRUCTION_DEPENDS_ON_TEE: parameter '{path}.{key}' "
                        f"references TEE output. Benchmark construction MUST NOT "
                        f"consume TEE performance results."
                    )
                check_recursive(value, f"{path}.{key}")
        elif isinstance(obj, list):
            for i, item in enumerate(obj):
                check_recursive(item, f"{path}[{i}]")

    check_recursive(params)


def deterministic_sample(
    candidates: List[dict],
    external_seed: str,
    target_n: int,
    domain_constraints: Optional[Dict[str, int]] = None,
    max_per_independence_group: int = 1,
) -> Tuple[List[dict], str]:
    """Deterministically sample candidates using an external seed.

    Args:
        candidates: List of candidate case dicts (must have case_id, domain, independence_group)
        external_seed: Externally supplied seed (NOT from TEE, NOT from benchmark contents)
        target_n: Target number of cases (minimum)
        domain_constraints: Optional dict of {domain: min_count}
        max_per_independence_group: Max cases from same independence_group (default 1)

    Returns:
        Tuple of (selected_cases, seed_hash)
    """
    # Validate seed is not empty
    if not external_seed:
        raise ValueError("EXTERNAL_SEED_EMPTY: seed must be non-empty")

    # Compute seed hash for reproducibility
    seed_hash = hashlib.sha256(external_seed.encode('utf-8')).hexdigest()

    # Check for duplicates
    seen_ids = set()
    for c in candidates:
        cid = c["case_id"]
        if cid in seen_ids:
            raise DuplicateCaseError(f"DUPLICATE_CASE: {cid}")
        seen_ids.add(cid)

    # Check domain coverage (using canonical domains for consistency)
    from .domain_taxonomy import canonicalize_domain
    canonical_domains = set(canonicalize_domain(c["domain"]) for c in candidates)
    if domain_constraints:
        for domain, min_count in domain_constraints.items():
            canon_domain = canonicalize_domain(domain)
            if canon_domain not in canonical_domains:
                raise InsufficientDomainsError(
                    f"INVALID_DOMAIN: required canonical domain '{canon_domain}' "
                    f"(from '{domain}') not in corpus"
                )

    # Check independence groups
    group_counts: Dict[str, int] = {}
    for c in candidates:
        group = c["independence_group"]
        group_counts[group] = group_counts.get(group, 0) + 1

    # Filter candidates by independence constraint
    # If max_per_independence_group=1, only one case per group is eligible
    eligible = []
    group_selected: Dict[str, int] = {}
    for c in candidates:
        group = c["independence_group"]
        if group_selected.get(group, 0) < max_per_independence_group:
            eligible.append(c)
            group_selected[group] = group_selected.get(group, 0) + 1  # FIX: actually increment

    # Check sufficient eligible cases
    if len(eligible) < target_n:
        raise InsufficientCorpusError(
            f"INSUFFICIENT_CORPUS: {len(eligible)} eligible cases "
            f"(need {target_n}). Independence constraint removed "
            f"{len(candidates) - len(eligible)} cases."
        )

    # Check domain count (using canonical domains for consistency)
    eligible_canon_domains = set(canonicalize_domain(c["domain"]) for c in eligible)
    min_domains = 4  # Per protocol: >=4 unrelated domains
    if len(eligible_canon_domains) < min_domains:
        raise InsufficientDomainsError(
            f"INSUFFICIENT_DOMAINS: {len(eligible_canon_domains)} canonical domains "
            f"(need {min_domains}). Raw domains: {sorted(set(c['domain'] for c in eligible))}"
        )

    # Deterministic sampling using seed
    # Sort candidates by case_id for determinism, then use seed-based shuffle
    eligible_sorted = sorted(eligible, key=lambda c: c["case_id"])

    # Seed-based PRNG (deterministic, reproducible)
    rng_state = int(seed_hash[:16], 16)  # Use first 64 bits of seed hash

    def seeded_random():
        nonlocal rng_state
        # Linear congruential generator (deterministic, simple)
        rng_state = (1103515245 * rng_state + 12345) % (2**31)
        return rng_state / (2**31)

    # Fisher-Yates shuffle with seeded PRNG
    shuffled = list(eligible_sorted)
    for i in range(len(shuffled) - 1, 0, -1):
        j = int(seeded_random() * (i + 1))
        shuffled[i], shuffled[j] = shuffled[j], shuffled[i]

    # Select cases, respecting domain constraints
    selected = []
    domain_counts: Dict[str, int] = {}

    # First pass: satisfy domain constraints
    if domain_constraints:
        for domain, min_count in domain_constraints.items():
            domain_cases = [c for c in shuffled if c["domain"] == domain]
            for c in domain_cases[:min_count]:
                if c not in selected:
                    selected.append(c)
                    domain_counts[domain] = domain_counts.get(domain, 0) + 1

    # Second pass: fill remaining slots
    for c in shuffled:
        if len(selected) >= target_n:
            break
        if c not in selected:
            selected.append(c)
            domain_counts[c["domain"]] = domain_counts.get(c["domain"], 0) + 1

    if len(selected) < target_n:
        raise InsufficientCorpusError(
            f"INSUFFICIENT_CORPUS: could only select {len(selected)} cases "
            f"(need {target_n})"
        )

    return selected, seed_hash


def construct_benchmark(
    corpus: List[dict],
    external_seed: str,
    target_n: int = 100,
    domain_constraints: Optional[Dict[str, int]] = None,
    construction_parameters: Optional[dict] = None,
) -> dict:
    """Construct a benchmark from corpus using external seed.

    This function has NO dependency on TEE output.
    """
    # Validate construction parameters don't reference TEE
    if construction_parameters:
        validate_construction_params(construction_parameters)

    selected, seed_hash = deterministic_sample(
        candidates=corpus,
        external_seed=external_seed,
        target_n=target_n,
        domain_constraints=domain_constraints,
    )

    # Compute corpus hash
    from .hasher import sha256_json
    corpus_hash = sha256_json(corpus)

    return {
        "selected_cases": selected,
        "case_count": len(selected),
        "domain_count": len(set(c["domain"] for c in selected)),
        "seed_hash": seed_hash,
        "corpus_hash": corpus_hash,
        "sampler_version": SAMPLER_VERSION,
        "construction_parameters": construction_parameters or {},
    }
