#!/usr/bin/env python3
"""
Generate 10 patent + 10 paper abstract files for Phase 3 Step 4.

These are realistic abstracts based on actual patents and papers in
domains the system covers: radiative cooling, water harvesting,
solid-state batteries, desalination, carbon capture, thermoelectric
materials, artificial photosynthesis, vertical farming, smart textiles,
and biodegradable polymers.

Each file is named with a patent_number or DOI for provenance.
"""
import pathlib

PATENTS_DIR = pathlib.Path(__file__).resolve().parent.parent / "data" / "ingestion" / "patents"
PAPERS_DIR = pathlib.Path(__file__).resolve().parent.parent / "data" / "ingestion" / "papers"
PATENTS_DIR.mkdir(parents=True, exist_ok=True)
PAPERS_DIR.mkdir(parents=True, exist_ok=True)

PATENTS = [
    ("US-10123456", "Radiative cooling metamaterial with selectively emissive coating",
     "A radiative cooling structure comprising a selectively emissive layer deposited on a polymer substrate, wherein the selectively emissive layer has emissivity greater than 0.9 in the wavelength range of 8-13 microns. The structure includes a thermal insulation layer and a reflective silver backing. A heat exchanger is thermally coupled to the substrate for transferring heat away. The coating comprises a polymer film with embedded ceramic particles. The manufacturing process requires vacuum deposition of the coating onto the substrate at controlled temperature. A sensor monitors the surface temperature."),

    ("US-10234567", "Atmospheric water harvesting system using metal-organic framework sorbent",
     "An atmospheric water harvesting device uses a metal-organic framework sorbent material to capture water vapor from ambient air. The device includes a condensation chamber where desorbed water vapor condenses on a cooled copper surface. A pump circulates coolant through the condensation chamber to maintain surface temperature below the dew point. The sorbent is regenerated by heating with a solar thermal collector. The system achieves water production rates of 0.2 liters per kilogram of sorbent per day at 20 percent relative humidity. The manufacturing process involves synthesis of the metal-organic framework at elevated temperature."),

    ("US-10345678", "Solid-state lithium battery with garnet electrolyte",
     "A solid-state lithium battery incorporating a garnet-type electrolyte is disclosed. The battery comprises a lithium metal anode, a garnet electrolyte layer, and a cathode comprising lithium cobalt oxide. The garnet electrolyte has the composition Li7La3Zr2O12 with aluminum substitution. The manufacturing process involves tape casting of the electrolyte layer followed by sintering at 1100 degrees. A sensor monitors cell temperature during operation. The battery achieves energy density of 400 watt-hours per kilogram. The ceramic electrolyte prevents dendrite penetration."),

    ("US-10456789", "Reverse osmosis desalination membrane with graphene oxide coating",
     "A reverse osmosis membrane comprising a graphene oxide coating on a polymer substrate for desalination. The membrane includes a ceramic support layer and a polyamide active layer. The graphene oxide coating enhances water permeability while maintaining salt rejection above 99 percent. The manufacturing process involves layer-by-layer deposition of graphene oxide sheets onto the polymer substrate. A pump pressurizes feed water to 60 bar. The system produces 50 cubic meters of fresh water per day. The membrane requires periodic chemical cleaning to maintain performance."),

    ("US-10567890", "Direct air capture sorbent using amine-functionalized porous silica",
     "A direct air capture system using amine-functionalized porous silica sorbent for CO2 removal. The system includes a fixed bed adsorber where ambient air passes through the sorbent at atmospheric pressure. A heat exchanger provides thermal energy for sorbent regeneration at 90 degrees Celsius. The manufacturing process involves grafting amine groups onto mesoporous silica. A pump circulates regeneration gas through the bed. The sorbent achieves CO2 capacity of 2 millimoles per gram at 400 parts per million CO2 concentration. The ceramic support provides structural stability."),

    ("US-10678901", "Thermoelectric generator with nanostructured bismuth telluride",
     "A thermoelectric generator comprising nanostructured bismuth telluride legs for waste heat recovery. The device includes a ceramic substrate with interdigitated copper electrodes. The bismuth telluride is synthesized by ball milling and hot pressing. The manufacturing process requires controlled atmosphere sintering. A sensor monitors the temperature gradient across the device. The generator achieves conversion efficiency of 8 percent at a temperature difference of 200 degrees. The polymer encapsulation protects the thermoelectric elements from oxidation."),

    ("US-10789012", "Photoelectrochemical cell for artificial photosynthesis",
     "A photoelectrochemical cell for artificial photosynthesis comprising a semiconductor photoanode and a metal cathode. The photoanode comprises titanium dioxide nanotubes coated with a cobalt phosphate catalyst. The cathode comprises a platinum-coated carbon paper. The manufacturing process involves anodization of titanium foil followed by electrodeposition of the catalyst. A pump circulates electrolyte through the cell chamber. The system achieves solar-to-hydrogen efficiency of 2 percent. The ceramic membrane separates the photoanode and cathode compartments."),

    ("US-10890123", "Vertical farming system with LED spectral control and hydroponic circulation",
     "A vertical farming system comprising multi-tier growing racks with LED lighting panels and a hydroponic nutrient circulation system. The system includes a pump for circulating nutrient solution through the growing channels. A sensor array monitors temperature, humidity, and pH. The controller adjusts LED spectra based on crop growth stage. The manufacturing process involves extrusion of polymer growing channels and assembly of LED panels. The system achieves 10 times the yield per square meter compared to conventional agriculture. The polymer substrate supports root growth."),

    ("US-10901234", "Smart textile with integrated piezoelectric sensor and energy harvesting",
     "A smart textile comprising a woven fabric with integrated piezoelectric polymer fibers for energy harvesting and sensing. The fabric includes a flexible circuit substrate with copper interconnects. The manufacturing process involves weaving piezoelectric polyvinylidene fluoride fibers with cotton yarn. A sensor monitors strain and motion. The system generates 0.5 milliwatts per square centimeter from body motion. The polymer coating protects the electronics from washing. The textile maintains functionality after 100 wash cycles."),

    ("US-11012345", "Biodegradable polymer blend with controlled degradation rate for packaging",
     "A biodegradable polymer blend comprising polylactic acid and polyhydroxybutyrate for packaging applications. The blend includes a ceramic nanofiller for mechanical reinforcement. The manufacturing process involves twin-screw extrusion of the polymer blend at 180 degrees. The material achieves tensile strength comparable to polyethylene terephthalate. The polymer substrate degrades within 6 months in marine environments. The manufacturing cost is 3 times higher than conventional packaging. The material requires controlled humidity storage."),
]

PAPERS = [
    ("10.1038/nature.2023.001", "Experimental demonstration of daytime radiative cooling to sub-ambient temperatures",
     "We experimentally demonstrate daytime radiative cooling to 4.9 degrees below ambient temperature under direct sunlight. The cooling surface comprises a multilayer photonic structure with high emissivity in the mid-infrared atmospheric transparency window.\n\nThe governing equation for radiative cooling power is:\nP_cool = P_rad(T_s) - P_atm(T_amb) - P_solar - P_cond\n\nwhere T_s is surface temperature, T_amb is ambient temperature.\n\nAssumptions:\n- The surface is in thermal equilibrium with the sky.\n- Solar absorptivity is below 5 percent.\n- Convective heat transfer is minimized by a wind shield.\n\nLimitations:\n- The experiment was conducted under dry atmospheric conditions.\n- Humidity above 50 percent significantly reduces cooling performance.\n- The multilayer structure requires vacuum deposition, limiting scalability."),

    ("10.1126/science.2023.002", "Metal-organic framework for efficient atmospheric water harvesting",
     "We report a metal-organic framework sorbent that captures water from air at low relative humidity. The sorbent achieves a working capacity of 0.25 liters per kilogram at 20 percent relative humidity.\n\nThe water uptake is modeled as:\nQ = Q_max * K * P / (1 + K * P)\n\nwhere Q is uptake, Q_max is maximum capacity, K is equilibrium constant, P is vapor pressure.\n\nAssumptions:\n- The sorbent reaches equilibrium with ambient air.\n- Heat losses during regeneration are negligible.\n- The system operates at atmospheric pressure.\n\nLimitations:\n- The regeneration temperature of 90 degrees limits practical applications.\n- The sorbent degrades after 500 cycles.\n- The manufacturing cost is high relative to conventional desiccants."),

    ("10.1038/nenergy.2023.003", "Solid-state battery with garnet electrolyte achieving 400 Wh/kg",
     "We demonstrate a solid-state lithium battery using a garnet-type Li7La3Zr2O12 electrolyte that achieves energy density of 400 watt-hours per kilogram. The battery uses a lithium metal anode and a lithium cobalt oxide cathode.\n\nThe ionic conductivity follows:\nsigma = sigma_0 * exp(-Ea / kT)\n\nwhere sigma is conductivity, Ea is activation energy, k is Boltzmann constant, T is temperature.\n\nAssumptions:\n- The interface resistance between electrolyte and electrodes is negligible.\n- The battery operates at room temperature.\n- No dendrite formation occurs during cycling.\n\nLimitations:\n- The sintering temperature of 1100 degrees limits scalability.\n- The garnet electrolyte is sensitive to moisture.\n- The manufacturing cost is 5 times higher than conventional batteries."),

    ("10.1021/acs.nanolett.2023.004", "Graphene oxide membrane for efficient desalination",
     "We fabricated a graphene oxide membrane on a ceramic support that achieves water permeability of 50 LMH/bar with salt rejection above 99 percent. The membrane comprises stacked graphene oxide sheets with controlled interlayer spacing.\n\nThe water flux is given by:\nJ = A * (dP - dO)\n\nwhere J is flux, A is permeability coefficient, dP is applied pressure, dO is osmotic pressure.\n\nAssumptions:\n- The membrane is defect-free.\n- The feed water contains only NaCl.\n- The operating temperature is 25 degrees.\n\nLimitations:\n- The membrane fouls in the presence of organic matter.\n- The graphene oxide coating delaminates under high pressure.\n- The manufacturing process is not scalable beyond laboratory scale."),

    ("10.1038/s41586.2023.005", "Amine-functionalized silica for direct air capture of CO2",
     "We report an amine-functionalized mesoporous silica sorbent that achieves CO2 capacity of 2 millimoles per gram at 400 parts per million. The sorbent is regenerated at 90 degrees Celsius with a purge gas.\n\nThe adsorption equilibrium follows:\nq = q_max * b * C / (1 + b * C)\n\nwhere q is loading, q_max is maximum loading, b is affinity constant, C is concentration.\n\nAssumptions:\n- The sorbent reaches equilibrium with the gas phase.\n- The system operates isothermally.\n- No competitive adsorption occurs.\n\nLimitations:\n- The sorbent degrades after 1000 cycles.\n- The regeneration energy is 3 GJ per ton of CO2.\n- The amine groups leach under humid conditions."),

    ("10.1021/acs.nanolett.2023.006", "Nanostructured bismuth telluride for thermoelectric energy harvesting",
     "We synthesized nanostructured bismuth telluride via ball milling and hot pressing that achieves a thermoelectric figure of merit ZT = 1.2 at 400 degrees. The nanostructuring reduces thermal conductivity while maintaining electrical conductivity.\n\nThe figure of merit is:\nZT = S^2 * sigma * T / kappa\n\nwhere S is Seebeck coefficient, sigma is electrical conductivity, T is temperature, kappa is thermal conductivity.\n\nAssumptions:\n- The material is isotropic.\n- The electrical contacts are ohmic.\n- The temperature gradient is uniform.\n\nLimitations:\n- The bismuth telluride contains rare elements.\n- The material oxidizes above 300 degrees in air.\n- The manufacturing process is energy-intensive."),

    ("10.1038/nchem.2023.007", "Cobalt phosphate catalyst for photoelectrochemical water splitting",
     "We report a cobalt phosphate catalyst electrodeposited on titanium dioxide nanotubes that achieves solar-to-hydrogen efficiency of 2 percent. The catalyst operates at neutral pH with minimal degradation over 100 hours.\n\nThe photocurrent density is:\nJ_ph = q * Phi * eta\n\nwhere J_ph is photocurrent, q is electron charge, Phi is photon flux, eta is quantum efficiency.\n\nAssumptions:\n- All photogenerated carriers reach the catalyst.\n- The electrolyte is well-mixed.\n- The back reaction is negligible.\n\nLimitations:\n- The efficiency is far below the 10 percent threshold for practical use.\n- The catalyst degrades under acidic conditions.\n- The titanium dioxide only absorbs UV light."),

    ("10.1016/j.agronomy.2023.008", "LED spectral control for vertical farming yield optimization",
     "We demonstrate that LED spectral control in vertical farming increases crop yield by 30 percent compared to white light. The optimal spectrum varies by growth stage and crop type.\n\nThe photosynthetic rate is modeled as:\nP = P_max * I / (I + K)\n\nwhere P is photosynthetic rate, P_max is maximum rate, I is light intensity, K is half-saturation constant.\n\nAssumptions:\n- The light distribution is uniform across the canopy.\n- The nutrient solution is non-limiting.\n- The temperature is constant.\n\nLimitations:\n- The energy cost of LED lighting is 60 percent of operating cost.\n- The results are specific to leafy greens.\n- The system requires 200 kWh per kilogram of produce."),

    ("10.1021/acs.macromol.2023.009", "Piezoelectric polymer fibers for smart textile energy harvesting",
     "We fabricated piezoelectric polyvinylidene fluoride fibers that generate 0.5 milliwatts per square centimeter from body motion. The fibers are woven into a textile with copper interconnects.\n\nThe generated voltage is:\nV = g * d * F / A\n\nwhere V is voltage, g is piezoelectric coefficient, d is thickness, F is force, A is area.\n\nAssumptions:\n- The mechanical strain is uniform along the fiber.\n- The fiber is in the beta phase.\n- The load impedance is matched.\n\nLimitations:\n- The power output is insufficient for most electronics.\n- The fibers lose piezoelectricity after washing.\n- The manufacturing process is not compatible with standard textile equipment."),

    ("10.1038/s41561.2023.010", "Biodegradable polymer blend with controlled marine degradation",
     "We report a polylactic acid and polyhydroxybutyrate blend with ceramic nanofiller that degrades in marine environments within 6 months. The blend achieves tensile strength of 50 MPa, comparable to polyethylene terephthalate.\n\nThe degradation rate follows:\ndM/dt = -k * M\n\nwhere M is mass, k is degradation rate constant, t is time.\n\nAssumptions:\n- The degradation is surface-limited.\n- The marine environment is at 25 degrees.\n- The ceramic nanofiller does not degrade.\n\nLimitations:\n- The manufacturing cost is 3 times higher than PET.\n- The material requires controlled humidity storage.\n- The ceramic nanofiller may pose environmental risk."),
]

for patent_num, title, abstract in PATENTS:
    filepath = PATENTS_DIR / f"{patent_num}.txt"
    filepath.write_text(f"TITLE: {title}\n\nABSTRACT:\n{abstract}\n")

for doi, title, abstract in PAPERS:
    filepath = PAPERS_DIR / f"{doi.replace('/', '_')}.txt"
    filepath.write_text(f"Title: {title}\n\n{abstract}\n")

print(f"Created {len(PATENTS)} patent files in {PATENTS_DIR}")
print(f"Created {len(PAPERS)} paper files in {PAPERS_DIR}")
