#!/usr/bin/env python3
"""protocol_a_power_calculation.py — Deterministic power calculation for Protocol A.

Per audit round 24:
    "The threshold/power section needs an independently verified statistical
     calculation, not a hand-written assertion. Those numbers should be
     generated by a small deterministic calculation and committed as a
     preregistration-support artifact."

This script computes the exact binomial power for Protocol A's design:
    N = 20 null cases
    Threshold: FPR_shuffled ≤ 0.20 (i.e., ≤ 4 out of 20 false positives)
    H0: FPR = 0.50 (random — shuffled bridge matches expected bridge 50% of time)
    H1: FPR = p for various values of p

The calculation is deterministic (no RNG, no simulation). It uses the
exact binomial CDF. The output is committed as a preregistration-support
artifact.

Usage:
    python3 scripts/protocol_a_power_calculation.py
    Output: experiments/measurement_discrimination/protocol_a_power.json
"""
import json
import math
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUTPUT = REPO / "experiments" / "measurement_discrimination" / "protocol_a_power.json"

# Protocol A parameters
N = 20  # number of null cases
THRESHOLD_FPR = 0.20  # FPR_shuffled ≤ 0.20 to pass
THRESHOLD_COUNT = int(N * THRESHOLD_FPR)  # = 4 (≤ 4 false positives out of 20)


def binomial_pmf(n, k, p):
    """Exact binomial probability mass function P(X=k | n, p)."""
    if k < 0 or k > n:
        return 0.0
    return math.comb(n, k) * (p ** k) * ((1 - p) ** (n - k))


def binomial_cdf(n, k, p):
    """Exact binomial cumulative distribution P(X ≤ k | n, p)."""
    return sum(binomial_pmf(n, i, p) for i in range(k + 1))


def power_at_fpr(true_fpr):
    """Power = P(observe ≤ threshold_count | true_fpr).

    This is the probability that the experiment declares LEXICALLY_SEPARABLE
    when the true false-positive rate is `true_fpr`.
    """
    return binomial_cdf(N, THRESHOLD_COUNT, true_fpr)


def type1_error(h0_fpr):
    """Type I error = P(declare LEXICALLY_SEPARABLE | H0 is true).

    H0: FPR = h0_fpr (the null hypothesis false-positive rate).
    If H0 is true, what's the probability of falsely declaring separability?
    """
    return binomial_cdf(N, THRESHOLD_COUNT, h0_fpr)


def main():
    print("Protocol A Power Calculation")
    print("=" * 60)
    print(f"N = {N} null cases")
    print(f"Threshold: FPR ≤ {THRESHOLD_FPR} (≤ {THRESHOLD_COUNT} out of {N})")
    print()

    # Compute power for a range of true FPR values
    fpr_values = [0.00, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.00]
    power_table = []

    for fpr in fpr_values:
        pwr = power_at_fpr(fpr)
        power_table.append({
            "true_fpr": fpr,
            "power": round(pwr, 6),
            "interpretation": interpret_power(fpr, pwr),
        })
        print(f"  FPR={fpr:.2f}: power={pwr:.4f} — {interpret_power(fpr, pwr)}")

    print()

    # Key thresholds
    power_at_0_10 = power_at_fpr(0.10)
    power_at_0_20 = power_at_fpr(0.20)
    power_at_0_25 = power_at_fpr(0.25)
    power_at_0_50 = power_at_fpr(0.50)

    print("Key values:")
    print(f"  Power at FPR=0.10 (good matcher): {power_at_0_10:.4f}")
    print(f"  Power at FPR=0.20 (threshold):    {power_at_0_20:.4f}")
    print(f"  Power at FPR=0.25 (marginal):     {power_at_0_25:.4f}")
    print(f"  Power at FPR=0.50 (random):       {power_at_0_50:.4f}")
    print()

    # Type I error under various H0
    print("Type I error (false positive rate of the TEST itself):")
    for h0 in [0.30, 0.40, 0.50]:
        t1 = type1_error(h0)
        print(f"  H0: FPR={h0:.2f}: P(false LEXICALLY_SEPARABLE) = {t1:.4f}")
    print()

    # Classification
    if power_at_0_10 >= 0.80:
        classification = "ADEQUATE_FOR_DETECTING_FPR_0.10"
    elif power_at_0_25 >= 0.80:
        classification = "ADEQUATE_FOR_DETECTING_FPR_0.25"
    else:
        classification = "EXPLORATORY_LOW_POWERED"

    print(f"Classification: {classification}")

    result = {
        "artifact_type": "PROTOCOL_A_POWER_CALCULATION",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "calculation_type": "EXACT_BINOMIAL (deterministic, no simulation, no RNG)",
        "protocol": "Protocol A — Lexical Matcher Discrimination",
        "parameters": {
            "n_null_cases": N,
            "threshold_fpr": THRESHOLD_FPR,
            "threshold_count": THRESHOLD_COUNT,
            "decision_rule": f"FPR_shuffled ≤ {THRESHOLD_FPR} (≤ {THRESHOLD_COUNT}/{N}) → LEXICALLY_SEPARABLE",
        },
        "power_table": power_table,
        "key_values": {
            "power_at_fpr_0.10": round(power_at_0_10, 6),
            "power_at_fpr_0.20": round(power_at_0_20, 6),
            "power_at_fpr_0.25": round(power_at_0_25, 6),
            "power_at_fpr_0.50": round(power_at_0_50, 6),
        },
        "type_1_error": {
            "h0_fpr_0.30": round(type1_error(0.30), 6),
            "h0_fpr_0.40": round(type1_error(0.40), 6),
            "h0_fpr_0.50": round(type1_error(0.50), 6),
        },
        "classification": classification,
        "interpretation": {
            "ADEQUATE_FOR_DETECTING_FPR_0.10": "N=20 has ≥80% power to detect FPR=0.10 (a good matcher with 10% accidental match rate). The experiment can confidently distinguish a good matcher from random.",
            "ADEQUATE_FOR_DETECTING_FPR_0.25": "N=20 has ≥80% power to detect FPR=0.25 but NOT FPR=0.10. The experiment can distinguish a poor matcher from random but cannot confidently verify a good matcher.",
            "EXPLORATORY_LOW_POWERED": "N=20 has <80% power even at FPR=0.25. The experiment is exploratory and cannot make confident claims about discrimination ability.",
        },
        "claim_limitation": "Protocol A tests LEXICAL separability only. It does NOT test discovery capability, cross-domain relationship discrimination, or engine competence. TPR_true = 1.0 by construction.",
        "mechanically_reproducible": True,
        "calculation_sha256": None,  # filled below
    }

    # Compute SHA-256 of the calculation
    import hashlib
    calc_str = json.dumps(result, sort_keys=True)
    result["calculation_sha256"] = hashlib.sha256(calc_str.encode()).hexdigest()

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(result, indent=2))
    print(f"\nPower calculation written to {OUTPUT}")
    print(f"SHA-256: {result['calculation_sha256'][:16]}...")


def interpret_power(fpr, power):
    if fpr <= 0.10 and power >= 0.80:
        return "ADEQUATE — can detect good matchers (FPR≤0.10) with ≥80% power"
    elif fpr <= 0.20 and power >= 0.80:
        return "ADEQUATE at threshold — can detect FPR=0.20 with ≥80% power"
    elif fpr <= 0.25 and power >= 0.50:
        return "MARGINAL — ~50% power at FPR=0.25"
    elif fpr >= 0.50 and power <= 0.05:
        return "GOOD Type I control — ≤5% false LEXICALLY_SEPARABLE under random H0"
    else:
        return "EXPLORATORY — insufficient power for confident claim"


if __name__ == "__main__":
    main()
