"""
PSCD-1 Outcome Ingestion — custodian-authenticated external outcomes only.

Never accepts:
  - mutable plaintext files
  - timestamps supplied only by the generator
  - outcomes generated by the same model that made the prediction
  - post-hoc manually edited outcome values
"""
import json, hashlib
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from typing import Optional


@dataclass
class Outcome:
    outcome_id: str
    prediction_id: str
    observed_value: str
    observed_at: str
    source: str
    source_hash: str
    confirmation_type: str  # INDEPENDENT_CONFIRMATION | PEER_REVIEWED | REGISTERED_RESULT | SYNTHETIC
    custodian_identity: str
    release_authorization_id: str
    outcome_artifact_hash: str
    release_timestamp: str
    generated_by_model: bool = False  # Must be False for acceptance
    is_foil: bool = False


def validate_outcome(o: Outcome) -> tuple[bool, list[str]]:
    """Validate a single outcome. Returns (ok, errors)."""
    errors = []
    if not o.outcome_id:
        errors.append("outcome_id is empty")
    if not o.prediction_id:
        errors.append("prediction_id is empty")
    if not o.observed_value:
        errors.append("observed_value is empty")
    if not o.observed_at:
        errors.append("observed_at is empty")
    if not o.source:
        errors.append("source is empty")
    if not o.source_hash:
        errors.append("source_hash is empty")
    if not o.confirmation_type:
        errors.append("confirmation_type is empty")
    if not o.custodian_identity:
        errors.append("custodian_identity is empty")
    if not o.release_authorization_id:
        errors.append("release_authorization_id is empty")
    if not o.outcome_artifact_hash:
        errors.append("outcome_artifact_hash is empty")
    if not o.release_timestamp:
        errors.append("release_timestamp is empty")
    if o.generated_by_model:
        errors.append("generated_by_model is True — self-generated outcomes are not accepted")
    return (len(errors) == 0, errors)


def verify_outcomes(predictions: list[dict], outcomes: list[Outcome],
                    prediction_freeze_timestamp: str) -> tuple[bool, list[str]]:
    """Verify outcomes against predictions. Returns (ok, errors)."""
    errors = []

    # 1. Every outcome must be valid
    for o in outcomes:
        ok, errs = validate_outcome(o)
        if not ok:
            errors.extend([f"{o.outcome_id}: {e}" for e in errs])

    # 2. No duplicate outcome IDs
    ids = [o.outcome_id for o in outcomes]
    if len(ids) != len(set(ids)):
        errors.append(f"Duplicate outcome IDs: {len(ids)} total, {len(set(ids))} unique")

    # 3. Every outcome's release_timestamp must be AFTER prediction_freeze_timestamp
    if prediction_freeze_timestamp:
        try:
            pf_ts = datetime.fromisoformat(prediction_freeze_timestamp.replace("Z", "+00:00"))
        except:
            pf_ts = None
        if pf_ts:
            for o in outcomes:
                try:
                    r_ts = datetime.fromisoformat(o.release_timestamp.replace("Z", "+00:00"))
                    if r_ts <= pf_ts:
                        errors.append(f"Outcome {o.outcome_id} released BEFORE prediction freeze")
                except:
                    errors.append(f"Cannot parse release_timestamp for {o.outcome_id}")

    # 4. No self-generated outcomes
    for o in outcomes:
        if o.generated_by_model:
            errors.append(f"Outcome {o.outcome_id} was generated by model — not accepted")

    return (len(errors) == 0, errors)
